from content.base import i

PAGE = dict(
    file="p-clause.html", key="cl", name="節・接続表現",
    icon="🧱",
    summary="名詞節・副詞節、時・条件・譲歩・目的・結果・理由、前置詞と接続詞、並列の範囲。",
    lead="節がどこからどこまでかを決めるのは、接続詞の仕事。接続詞の意味と、そのあとに続く形を整理する。",
    sections=[
    ("名詞節", [
        i("cl-noun-that", "must", "名詞節をつくる that",
          "that 節が、<b>S・O・C</b>、または<b>形容詞のあと</b>（感情の原因）になっているか。",
          [("It is true <mark>that he made a mistake</mark>.", "彼が間違えたのは本当だ。"),
           ("The problem is <mark>that we have no time</mark>.", "問題は、時間がないことだ。"),
           ("I was surprised <mark>that she came</mark>.", "彼女が来たことに驚いた。")],
          tip="that 節は<b>「〜ということ」</b>。動詞の目的語のときは that を省略できる。<b>主語・同格の that は省略しにくい</b>。",
          warn="前置詞の直後に that 節は置けない（例外は <b>in that 〜／except that 〜</b>）。"),
        i("cl-whether-if", "must", "whether / if（〜かどうか）",
          "<b>whether / if</b> が「〜かどうか」の名詞節を導く。",
          [("I don't know <mark>whether he will come (or not)</mark>.", "彼が来るかどうかわからない。"),
           ("The question is <mark>whether this plan is realistic</mark>.", "問題は、この計画が現実的かどうかだ。")],
          tip="<b>whether</b> は主語・補語・前置詞の目的語にもなれる。<b>if は主に動詞の目的語</b>（文頭の主語、前置詞の直後、if ... or not の形では使えない）。名詞節の中は、未来なら will を使う。",
          warn="副詞節の if（もし〜なら）と混同しない。<b>if の節に未来の will がある</b>なら、名詞節（かどうか）の目安になる（ただし If you will wait here のような、意志・丁寧の will は副詞節）。"),
        i("cl-indirect-question", "must", "間接疑問（疑問詞節）の語順と役割",
          "<b>疑問詞＋S＋V</b>が、文の一部になっている。",
          [("I wonder <mark>why he left so early</mark>.", "彼はなぜそんなに早く帰ったのだろうか。"),
           ("<mark>How we behave</mark> matters more than <mark>what we say</mark>.", "私たちがどう行動するかは、何を言うかよりも重要だ。")],
          tip="名詞節として、<b>S・O・C・前置詞の目的語</b>になる。節の中は S V の語順。文頭にあれば主語、動詞の後ろなら目的語。"),
    ]),
    ("時・条件・譲歩・理由・目的・結果", [
        i("cl-time-cond-present", "must", "時・条件の副詞節では、未来を現在形で表す",
          "<b>when / if / as soon as / before / after / unless</b> の節の中の動詞。",
          [("I will call you <mark>when I arrive</mark>.", "着いたら電話する。"),
           ("<mark>If it rains tomorrow</mark>, we will stay home.", "もし明日雨が降ったら、家にいる。")],
          tip="未来の内容でも、<b>時・条件の副詞節では現在形</b>を使う（× when I will arrive）。",
          warn="名詞節では未来を will で表す：I don't know <b>when he will arrive</b>.（いつ着くかわからない）。"),
        i("cl-time-conj", "must", "時を表す接続表現",
          "<b>by the time / every time / the moment / as soon as / once / until</b> などの意味の違い。",
          table=(["表現", "意味"], [
              ["by the time 〜", "〜するまでには"],
              ["every time / each time 〜", "〜するたびに"],
              ["the moment / the instant / the minute 〜", "〜するとすぐに（名詞が接続詞の働き）"],
              ["as soon as 〜", "〜するとすぐに"],
              ["once 〜", "いったん〜すると"],
              ["until / till 〜", "〜するまで（ずっと）"],
              ["since 〜", "〜して以来"]]),
          ex=[("<mark>By the time</mark> we arrived, the movie had already started.", "私たちが着くまでには、映画はもう始まっていた。"),
           ("<mark>The moment</mark> she saw him, she smiled.", "彼女は彼を見るとすぐに、微笑んだ。")],
          tip="<b>by と until の違い</b>：by は「期限（〜までに）」、until は「継続（〜までずっと）」。"),
        i("cl-hardly-when", "core", "hardly ... when / no sooner ... than（〜するとすぐに）",
          "<b>過去完了</b>と <b>when / before / than</b> が、セットで出る。",
          [("<mark>Hardly had I reached</mark> the station <mark>when</mark> the train left.", "駅に着くか着かないかのうちに、電車は出た。"),
           ("<mark>No sooner had he sat</mark> down <mark>than</mark> the phone rang.", "彼が座るやいなや、電話が鳴った。")],
          tip="<b>hardly / scarcely ... when（before）</b>、<b>no sooner ... than</b> ＝ 「〜するとすぐに…」。否定語が文頭に出ると、倒置（had ＋ S ＋ p.p.）になる。"),
        i("cl-not-until", "must", "not until ... / It is not until ... that ~",
          "<b>not until</b> のあとの節が、いつから起きるか。",
          [("<mark>It was not until</mark> I lost my health <mark>that</mark> I realized its value.", "健康を失って初めて、その価値に気づいた。"),
           ("<mark>Not until</mark> the rain stopped <mark>did we</mark> leave.", "雨が止むまで、私たちは出発しなかった。")],
          tip="<b>「〜して初めて…」「〜するまで…しない」</b>。not until が文頭にあると、主節が倒置（did we leave）になる。強調構文 It is not until ... that ~ の形も多い。"),
        i("cl-concession", "must", "譲歩（although / though / even if / even though）",
          "「たしかに〜だが」の<b>前半</b>にあたる節。",
          [("<mark>Although he was tired</mark>, he kept working.", "彼は疲れていたが、働き続けた。"),
           ("<mark>Even if it rains</mark>, we will go.", "たとえ雨が降っても、私たちは行く。")],
          tip="<b>even though ＝ 事実</b>（〜だけれども）、<b>even if ＝ 仮定</b>（たとえ〜だとしても）。譲歩のあとには<b>筆者の主張</b>が来ることが多い。",
          warn="Although と but は<b>ふつう併用しない</b>（× Although ..., but ...）。"),
        i("cl-whether-a-or-b", "core", "whether A or B（〜であろうとなかろうと）",
          "<b>whether ... or ...</b> が副詞節（譲歩）になっている。",
          [("<mark>Whether you like it or not</mark>, you have to do it.", "好むと好まざるとにかかわらず、あなたはそれをしなければならない。")],
          tip="or 以下は省略されることがある。<b>whether ... or not</b>。副詞節のときは「〜であろうとなかろうと」と訳す。"),
        i("cl-however-order", "core", "however＋形容詞・副詞、no matter＋wh-（語順）",
          "<b>However hard he tried,</b> のように、however の直後に形容詞・副詞が続く。",
          [("<mark>However hard he tried</mark>, he could not win.", "どんなに頑張っても、彼は勝てなかった。"),
           ("<mark>No matter how hard you try</mark>, you cannot please everyone.", "どんなに頑張っても、すべての人を喜ばせることはできない。")],
          tip="語順は<b>however ＋ 形容詞・副詞 ＋ S ＋ V</b>（＝ no matter how ＋ 形容詞・副詞 ＋ S ＋ V）。「どんなに〜でも」。"),
        i("cl-reason", "core", "理由（because / since / as / now that / in that）",
          "理由を表す接続詞の、<b>ニュアンスの違い</b>。",
          [("<mark>Now that you have finished</mark> the work, you can go home.", "仕事を終えたのだから、家に帰ってよい。"),
           ("Humans differ from animals <mark>in that</mark> they use language.", "人間は、言語を使うという点で動物と異なる。")],
          tip="<b>because</b> は新しい情報としての理由、<b>since / as</b> は文頭で「〜なので（相手も知っている理由）」。<b>in that 〜 ＝ 〜という点で</b>、<b>now that 〜 ＝ 今や〜だから</b>。"),
        i("cl-purpose", "must", "目的（so that / in order that）",
          "<b>so that 〜 can / will / may ...</b> のように、あとに助動詞が続く。",
          [("He spoke slowly <mark>so that everyone could understand</mark>.", "皆が理解できるように、彼はゆっくり話した。")],
          tip="<b>「〜するために・〜するように」</b>。so that の節の中には、<b>can / will / may</b> など助動詞（過去形も）がある。",
          warn="コンマつきの <b>, so that 〜</b> は「その結果〜」と結果を表すことがある。目的か結果かは、助動詞の有無と文脈で決める。"),
        i("cl-result", "must", "結果・程度（so ... that / such ... that）",
          "<b>so ＋形容詞・副詞</b> または <b>such ＋（a）＋形容詞＋名詞</b>のあとに、that 節。",
          [("The passage was <mark>so long that</mark> few students finished it.", "その文章はとても長かったので、読み終えた学生はほとんどいなかった。"),
           ("It was <mark>such a difficult book that</mark> I gave up.", "とても難しい本だったので、私はあきらめた。"),
           ("He was <mark>so kind as to</mark> help us.", "彼は親切にも私たちを助けてくれた。")],
          tip="<b>「とても〜なので…」</b>。that は省略されることもある。<b>so ... as to do ＝ 〜するほど…（親切にも〜する）</b>も同じ仲間。"),
        i("cl-condition", "must", "条件（unless / as long as / in case / provided that）",
          "if 以外の、条件を表す接続表現。",
          [("<mark>Unless</mark> you hurry, you will miss the bus.", "急がないと、バスに乗り遅れる。"),
           ("You can borrow it <mark>as long as</mark> you return it by Friday.", "金曜日までに返しさえすれば、貸してあげる。"),
           ("Take an umbrella <mark>in case</mark> it rains.", "雨が降るといけないから、傘を持っていきなさい。")],
          tip="<b>unless ＝ if ... not</b>（〜しない限り）、<b>in case 〜 ＝ 〜するといけないから（備え）</b>、<b>as long as ＝ 〜しさえすれば</b>、<b>provided (that) 〜 ＝ もし〜ならば</b>。"),
        i("cl-manner", "core", "様態（as / as if / as though）",
          "<b>as</b> が「〜のように」、<b>as if</b> が「まるで〜であるかのように」。",
          [("Do <mark>as you like</mark>.", "好きなようにしなさい。"),
           ("He talks <mark>as if he knew</mark> everything.", "彼はまるで何でも知っているかのように話す。")],
          tip="<b>as if ＋ 仮定法</b>（事実と反対）が基本。<b>It looks as if it will rain.</b> のように、実際にそう見えるときは、直説法も使う。"),
        i("cl-range", "core", "範囲・限度（as far as / as long as）",
          "<b>as far as 〜</b> と <b>as long as 〜</b> の使い分け。",
          [("<mark>As far as I know</mark>, he is honest.", "私の知る限り、彼は正直だ。"),
           ("<mark>As long as I live</mark>, I will never forget this.", "生きている限り、私はこのことを決して忘れない。")],
          tip="<b>as far as ＝ 範囲・限度</b>（私の知る限り）、<b>as long as ＝ 期間・条件</b>（〜する間は／〜しさえすれば）。"),
        i("cl-contrast", "core", "while / whereas（対比）",
          "<b>while</b> が「〜する間」ではなく、<b>対比</b>を表している。",
          [("Some people like cities, <mark>while</mark> others prefer the countryside.", "都会が好きな人もいれば、田舎を好む人もいる。")],
          tip="<b>while</b> は、①時（〜する間）②対比（〜である一方で）③譲歩（〜だけれども）。<b>文全体の意味</b>で決める。<b>whereas</b> は対比（〜である一方で）。"),
    ]),
    ("接続詞・前置詞・並列", [
        i("cl-prep-conj", "must", "前置詞と接続詞のペア",
          "<b>後ろが S＋V か、名詞だけか</b>で使い分ける。",
          table=(["意味", "接続詞（＋S V）", "前置詞（＋名詞）"], [
              ["理由", "because", "because of / due to / owing to"],
              ["譲歩", "although / though", "despite / in spite of"],
              ["期間（〜の間）", "while", "during"],
              ["条件（〜がなければ）", "unless", "without"],
              ["対比", "whereas", "—"]]),
          ex=[("We stayed home <mark>because of</mark> the rain.", "雨のために、私たちは家にいた。"),
           ("We stayed home <mark>because</mark> it was raining.", "雨が降っていたので、私たちは家にいた。")],
          warn="<b>because of ＋ S V</b>、<b>despite ＋ S V</b> は誤り。後ろが節なら接続詞、名詞（句）なら前置詞。"),
        i("cl-coordination", "must", "and / but / or がつなぐ範囲",
          "接続詞の<b>前後で、同じ形のもの</b>がつながっている。",
          [("He <mark>opened the door</mark>, <mark>looked around</mark>, and <mark>stepped inside</mark>.", "彼はドアを開け、辺りを見回し、中に入った。"),
           ("She likes <mark>reading books</mark> and <mark>watching movies</mark>.", "彼女は本を読むことと映画を見ることが好きだ。")],
          tip="and の後ろの形（動詞句・名詞・節）と<b>同じ形のものを、前から探す</b>。<b>並列の範囲</b>が決まれば、意味のまとまりが見える。"),
        i("cl-correlative", "must", "相関接続詞（both A and B など）",
          "対になっている接続表現。<b>A と B は同じ形</b>。",
          table=(["表現", "意味"], [
              ["both A and B", "AもBも両方"],
              ["either A or B", "AかBのどちらか"],
              ["neither A nor B", "AもBも〜ない"],
              ["not only A but also B（＝ B as well as A）", "AだけでなくBも"],
              ["not A but B", "AではなくB"]]),
          tip="<b>either A or B / neither A nor B / not only A but also B</b> では、動詞は<b>B に一致</b>させる。<b>both A and B は複数扱い</b>、<b>B as well as A は B（前の語）に一致</b>。"),
        i("cl-so-for-yet", "core", "so / for / yet / nor",
          "等位接続詞の意味の違い。",
          [("It was raining, <mark>so</mark> we stayed home.", "雨が降っていたので、私たちは家にいた。"),
           ("He was sad, <mark>for</mark> he had lost his dog.", "彼は悲しかった。というのは、犬を失ったからだ。"),
           ("She is young, <mark>yet</mark> she is wise.", "彼女は若いが、賢い。")],
          tip="<b>so ＝ だから（結果）</b>、<b>for ＝ というのは〜だから（理由の補足）</b>、<b>yet ＝ しかし（逆接）</b>、<b>nor ＝ 〜もまた…ない（倒置）</b>。"),
        i("cl-as-usage", "core", "接続詞 as の意味の決め方",
          "as は意味が多い。<b>まず「時・理由」で読んで、通らなければ他を試す</b>。",
          table=(["意味", "例"], [
              ["時（〜するとき／〜しながら）", "She smiled <b>as</b> she opened the door."],
              ["理由（〜なので）", "<b>As</b> it was late, we went home."],
              ["比例（〜につれて）", "<b>As</b> you learn more, you notice more."],
              ["様態（〜のように）", "Do <b>as</b> you are told."],
              ["譲歩（〜だけれども）", "Young <b>as</b> he was, he led the team."]]),
          tip="<b>比較級と一緒</b>なら比例（〜につれて）、<b>形容詞＋as＋S V</b>なら譲歩。"),
    ]),
    ],
    quiz=[
        ("次の文を訳しなさい。<br><i>Not until he left the room did I notice the mistake.</i>",
         "<p><b class=\"a\">彼が部屋を出て初めて、私はその間違いに気づいた。</b></p><p>Not until が文頭で、did I notice と倒置している。</p>"),
        ("次の2文の意味の違いを説明しなさい。<br><i>She spoke loudly so that everyone could hear her. ／ She spoke so loudly that everyone could hear her.</i>",
         "<p><b class=\"a\">前者：皆が聞こえるように、大声で話した（目的）／後者：とても大声で話したので、皆に聞こえた（結果）</b></p><p>so that は目的（助動詞を伴う）、so ＋副詞 ＋ that は結果・程度。</p>"),
        ("（　）に入る語を答えなさい。<br><i>The train was delayed (　　　) the heavy snow.</i>　ア. because　イ. because of",
         "<p><b class=\"a\">イ. because of</b></p><p>後ろが名詞（the heavy snow）なので前置詞。because は後ろに S＋V が必要。</p>"),
        ("言い換えなさい。<br><i>Don't go out unless it stops raining.</i>（if を使って）",
         "<p><b class=\"a\">Don't go out if it does not stop raining.</b></p><p>unless ＝ if ... not。</p>"),
    ],
)
