from content.base import i

PAGE = dict(
    file="p-compare.html", key="cp", name="比較",
    icon="⚖️",
    summary="原級・比較級・最上級、最上級相当表現、no more than、not so much A as B、比較の対象。",
    lead="「何と何を比べているか」を、まず決める。比較の構文は形が決まっているので、型で覚えるのが早い。",
    sections=[
    ("基本の形", [
        i("cp-as-as", "must", "原級 as ... as と倍数表現",
          "<b>as ＋ 形容詞・副詞 ＋ as</b>。",
          ex=[("He runs <mark>as fast as</mark> I do.", "彼は私と同じくらい速く走る。"),
           ("This is <mark>not so difficult as</mark> I expected.", "これは私が思っていたほど難しくない。"),
           ("This room is <mark>twice as large as</mark> that one.", "この部屋はあの部屋の2倍の広さだ。"),
           ("<mark>As many as</mark> 500 people attended.", "500人もの人が出席した。")],
          tip="<b>not as（so）... as ＝ 〜ほど…ではない</b>。<b>倍数 ＋ as ... as ＝ 〜の○倍</b>。<b>as many / much as ＝ 〜もの</b>（数量が多いという気持ち）。"),
        i("cp-comparative", "must", "比較級 than と、比較級の強調",
          "<b>比較級 ＋ than</b>。強調の語が前についていないか。",
          ex=[("This book is <mark>much more interesting</mark> than that one.", "この本はあの本よりずっとおもしろい。"),
           ("He is <mark>even taller</mark> than his father.", "彼は父親よりさらに背が高い。"),
           ("He is <mark>two years older</mark> than I.", "彼は私より2歳年上だ。")],
          tip="比較級の強調は <b>much / far / still / even / a lot</b>。<b>very は使えない</b>（× very better）。差は<b>比較級の前</b>に置く（two years older）。"),
        i("cp-the-more", "must", "the ＋比較級 ..., the ＋比較級 ~",
          "文が <b>The 比較級</b> で始まり、コンマのあとにも <b>the 比較級</b>。",
          ex=[("<mark>The more</mark> you read, <mark>the more</mark> you learn.", "読めば読むほど、学ぶことが増える。"),
           ("<mark>The sooner</mark>, <mark>the better</mark>.", "早ければ早いほどよい。")],
          tip="<b>「〜すればするほど、ますます…」</b>。前半が条件、後半が結果。主語と動詞が省略されることもある。"),
        i("cp-superlative", "must", "最上級と、その強調",
          "<b>the ＋最上級 ＋ in / of 〜</b>。",
          ex=[("She is <mark>the tallest</mark> girl <mark>in her class</mark>.", "彼女はクラスでいちばん背が高い。"),
           ("This is <mark>by far the best</mark> restaurant in town.", "ここは町で断然いちばんのレストランだ。"),
           ("This is the most beautiful place <mark>I have ever visited</mark>.", "ここは私が今までに訪れた中でいちばん美しい場所だ。")],
          tip="<b>in ＋ 場所・集団、of ＋ 複数のもの</b>で範囲を示す。強調は <b>by far / much / the very</b>。<b>ever ＋ 現在完了</b>は最上級とよく組む。<b>同じ人・ものの中で状態を比べる</b>とき（The lake is deepest here.）や、<b>副詞の最上級</b>（He runs (the) fastest.）では、the を付けないことがある。"),
        i("cp-superlative-equivalent", "must", "最上級と同じ意味になる表現",
          "<b>Nothing is more ... than 〜</b>、<b>No other ... is as ... as 〜</b>。",
          ex=[("<mark>Nothing is more important than</mark> health.", "健康より大切なものはない。（＝健康がいちばん大切だ）"),
           ("<mark>No other city in Japan is as large as</mark> Tokyo.", "日本の他のどの都市も東京ほど大きくない。（＝東京が最大だ）"),
           ("He is taller <mark>than any other boy</mark> in his class.", "彼はクラスの他のどの男の子よりも背が高い。")],
          tip="<b>否定文で比べる ＝ 最上級の意味</b>。訳すときは「最も〜」と読み替える。<b>than any other ＋ 単数名詞</b>も同じ。"),
    ]),
    ("重要な比較表現", [
        i("cp-no-more-than", "must", "no more than / not more than / no less than / not less than",
          "<b>no</b> は「気持ちを込めた断定」、<b>not</b> は「客観的な範囲」。",
          table=(["表現", "意味", "例"], [
              ["no more than 〜", "〜しかない（少ない）", "He had <b>no more than</b> ten yen."],
              ["not more than 〜", "多くても〜（せいぜい）", "It takes <b>not more than</b> ten minutes."],
              ["no less than 〜", "〜も（多い）", "She read <b>no less than</b> fifty books."],
              ["not less than 〜", "少なくとも〜", "It takes <b>not less than</b> an hour."]]),
          tip="<b>no ＝ 強い断定（少ない・多い）</b>、<b>not ＝ 客観的な上限・下限（以下・以上）</b>。"),
        i("cp-not-so-much", "must", "not so much A as B / B rather than A",
          "<b>AというよりむしろB</b>を表す型。",
          ex=[("He is <mark>not so much a scholar as a teacher</mark>.", "彼は学者というよりむしろ教師だ。"),
           ("He is <mark>more a poet than a scientist</mark>.", "彼は科学者というより詩人だ。"),
           ("It was <mark>a warning rather than</mark> a threat.", "それは脅しというより、警告だった。")],
          tip="<b>not so much A as B ＝ more B than A ＝ B rather than A ＝ 「AというよりB」</b>。重点は<b>B</b>にある。<b>not so much as 〜（〜さえしない）</b>とは別の形なので、混同しない。"),
        i("cp-than-omitted", "must", "than の後ろの省略と、that of / those of",
          "<b>比べる相手</b>が、省略されたり、代名詞で言い換えられたりしている。",
          ex=[("The population of Tokyo is larger than <mark>that of</mark> Osaka.", "東京の人口は、大阪の人口より多い。"),
           ("Prices here are higher than <mark>those in</mark> Tokyo.", "ここの物価は、東京の物価より高い。"),
           ("His English is better than <mark>mine</mark>.", "彼の英語は、私の英語よりも上手だ。")],
          tip="<b>that ＝ 単数名詞、those ＝ 複数名詞</b>の繰り返しを避ける。比べるものは同じ種類（× the population of Tokyo is larger than Osaka）。than の後ろの<b>S や V の省略</b>も補って読む。"),
        i("cp-idioms", "core", "比較級を使う慣用表現",
          "決まった形で意味を持つ、<b>比較級のかたまり</b>。",
          table=(["表現", "意味"], [
              ["more or less", "多かれ少なかれ"],
              ["sooner or later", "遅かれ早かれ"],
              ["no longer / not ... any longer", "もはや〜ない"],
              ["all the more (for / because)", "〜だからいっそう"],
              ["nonetheless（none the less）", "それでもやはり"],
              ["much less / still less", "まして〜ない"],
              ["more and more", "ますます"]]),
          ex=[("I like him <mark>all the more for</mark> his faults.", "欠点があるからこそ、彼がいっそう好きだ。")],
          tip="かたまりで覚える。<b>all the more ＋ for 理由／because 節</b>は、理由がある分だけ「いっそう」。"),
        i("cp-as-possible", "core", "as ... as possible / as ... as one can / as ... as ever",
          "<b>as ... as ＋ 決まった語句</b>。",
          ex=[("Please reply <mark>as soon as possible</mark>.", "できるだけ早く返事をください。"),
           ("He ran <mark>as fast as he could</mark>.", "彼はできるだけ速く走った。"),
           ("He is <mark>as kind as ever</mark>.", "彼は相変わらず親切だ。")],
          tip="<b>as ... as possible ＝ as ... as S can</b>（できるだけ〜）。<b>as ... as ever ＝ 相変わらず／これまでと同じく〜</b>。"),
        i("cp-latin", "core", "than を使わない比較（superior to / prefer A to B）",
          "比較の相手を <b>to</b> で示す語。",
          ex=[("This model is <mark>superior to</mark> the older one.", "このモデルは古いものより優れている。"),
           ("I <mark>prefer</mark> tea <mark>to</mark> coffee.", "私はコーヒーより紅茶が好きだ。")],
          tip="<b>superior / inferior / senior / junior / prefer ... to 〜</b>。than ではなく to を使う。強調は <b>much superior</b>。"),
        i("cp-of-the-two", "core", "the ＋比較級 of the two",
          "<b>2つのうち</b>で比べるとき、比較級にも the がつく。",
          ex=[("Tom is <mark>the taller of the two</mark>.", "トムは2人のうちの背の高いほうだ。")],
          tip="<b>the ＋比較級 ＋ of the two</b>。3つ以上なら最上級を使う。"),
        i("cp-as-good-as", "core", "as good as / may as well",
          "<b>as good as</b> が「〜も同然」、<b>may as well</b> が「〜したほうがよい」。",
          ex=[("He <mark>as good as</mark> promised.", "彼は約束したも同然だった。"),
           ("You <mark>might as well</mark> ask him.", "彼に聞いてみたらどうだ（聞いてもいいだろう）。")],
          tip="<b>as good as ＝ ほとんど〜も同然</b>。<b>may (might) as well do ＝ 〜したほうがいい</b>（消極的な提案）。"),
        i("cp-superlative-idioms", "core", "最上級を使う慣用表現",
          "<b>at (the) most / at least / at best</b> など。",
          table=(["表現", "意味"], [
              ["at (the) most", "せいぜい"],
              ["at least", "少なくとも"],
              ["at best / at worst", "よくても／悪くても"],
              ["at the latest / at the earliest", "遅くとも／早くとも"],
              ["for the most part", "たいていは"],
              ["make the most of 〜", "〜を最大限に活用する"]]),
          ex=[("It will take <mark>at least</mark> two hours.", "少なくとも2時間かかる。")],
          tip="<b>at most ＝ 上限、at least ＝ 下限</b>。数量を見積もる表現。"),
        i("cp-whale", "core", "クジラ構文（A is no more B than C is D）",
          "<b>no more ... than</b> が、「どちらも〜ない」を表す。",
          ex=[("A whale is <mark>no more</mark> a fish <mark>than</mark> a horse is.", "クジラが魚でないのは、馬が魚でないのと同じだ。")],
          tip="<b>A is no more B than C is D ＝ AがBでないのは、CがDでないのと同じ</b>。前後の否定を一緒に読む。<b>no less ... than</b> は「〜と同じく…だ」（肯定）。長文ではまれだが、文法・整序問題で出ることがある。"),
    ]),
    ],
    quiz=[
        ("次の文の意味を答えなさい。<br><i>He had no more than 1,000 yen.</i>",
         "<p><b class=\"a\">1,000円しか持っていなかった。</b></p><p>no more than ＝ 〜しかない（少ないという気持ち）。not more than なら「多くても1,000円」。</p>"),
        ("次の文を訳しなさい。<br><i>He is not so much a scholar as a teacher.</i>",
         "<p><b class=\"a\">彼は学者というよりむしろ教師だ。</b></p><p>not so much A as B ＝ AというよりB。</p>"),
        ("（　）に入る語を答えなさい。<br><i>The population of Tokyo is larger than (　　　) of Osaka.</i>",
         "<p><b class=\"a\">that</b></p><p>the population の繰り返しを避ける代名詞。複数名詞なら those。</p>"),
        ("次の文を「最も〜」の形で言い換えなさい。<br><i>Nothing is more important than health.</i>",
         "<p><b class=\"a\">Health is the most important thing.</b></p><p>否定文で比べる形は最上級と同じ意味。</p>"),
    ],
)
