from content.base import i

PAGE = dict(
    file="p-modifier.html", key="md", name="修飾（関係詞・後置修飾）",
    icon="🔗",
    summary="関係代名詞・関係副詞・what・複合関係詞、分詞や形容詞の後置修飾、名詞構文。",
    lead="名詞を後ろから説明する形が、長い英文のいちばんの難所。「どの名詞を、どこまでが説明しているか」を見抜く。",
    sections=[
    ("関係詞", [
        i("md-rel-basic", "must", "関係代名詞（主格・目的格・所有格）",
          "関係詞の<b>後ろに何が欠けているか</b>を見る。",
          table=(["格", "後ろの形", "例"], [
              ["主格 who / which / that", "<b>主語が欠けている</b>", "the student <b>who</b> won the prize"],
              ["目的格 whom / which / that", "<b>目的語が欠けている</b>", "the book <b>which</b> I bought"],
              ["所有格 whose", "<b>名詞</b>が続く（〜の）", "the man <b>whose</b> car was stolen"]]),
          tip="先行詞が<b>人なら who、ものなら which</b>（that はどちらにも使える）。関係詞節の中で、関係詞が S・O・所有のどれをしているかを決める。"),
        i("md-prep-rel", "must", "前置詞＋関係代名詞（in which / with whom）",
          "関係詞の<b>前に前置詞</b>があるとき、後ろは<b>完全な文</b>。",
          [("This is the house <mark>in which</mark> he was born.", "これは彼が生まれた家だ。（＝ the house which he was born in）"),
           ("The people <mark>with whom</mark> I work are kind.", "私が一緒に働いている人たちは親切だ。"),
           ("There were fifty students, <mark>most of whom</mark> passed the exam.", "50人の学生がいて、そのほとんどが試験に合格した。")],
          tip="前置詞は、関係詞節の動詞・名詞との結びつきで決まる（born <b>in</b> / work <b>with</b>）。<b>some / most / all / none of whom（which）</b>は「そのうちの〜」。",
          warn="前置詞の直後に <b>that は置けない</b>（× in that）。人なら whom、ものなら which。"),
        i("md-rel-adverb", "must", "関係副詞（where / when / why / how）",
          "先行詞が場所・時・理由・方法で、関係詞の後ろが<b>完全な文</b>。",
          [("This is the town <mark>where</mark> I grew up.", "ここは私が育った町だ。"),
           ("I remember the day <mark>when</mark> we first met.", "私たちが初めて会った日を覚えている。"),
           ("That is <mark>why</mark> he was late.", "そういうわけで、彼は遅れたのだ。")],
          tip="<b>That is why 〜 ＝ それが〜の理由だ（結果を述べる）</b>、<b>That is because 〜 ＝ それは〜だからだ（理由を述べる）</b>。「理由」と「結果」の向きに注意。",
          warn="<b>the reason why</b> は正しい形で、why は省略もできる（the reason he left）。<b>the way how は不可</b>で、<b>the way（か how のどちらか一方）</b>にする。また、先行詞が場所でも、<b>後ろが不完全なら関係代名詞 which</b>（the town which I visited）。"),
        i("md-rel-omit", "must", "関係詞の省略",
          "<b>名詞の後ろに S＋V が続いている</b>形。",
          [("The book <mark>(that) I read yesterday</mark> was interesting.", "私が昨日読んだ本はおもしろかった。"),
           ("The girl <mark>(who is) standing there</mark> is my sister.", "そこに立っている女の子は私の妹だ。")],
          tip="<b>目的格の関係詞</b>は省略できる。名詞が2つ並んだら（the book I read）、間に関係詞を補う。「関係詞＋be」も省略され、分詞や形容詞句の後置修飾になる。",
          warn="<b>主格の関係代名詞は、ふつう省略しない</b>（× The man lives next door is a doctor. ○ The man <b>who</b> lives next door is a doctor.）。ただし<a href=\"#md-chain-rel\">連鎖関係詞節</a>（the man I think is honest）は、I think を挟むので省略できる。"),
        i("md-nonrestrictive", "must", "非制限用法（コンマ＋関係詞）",
          "関係詞の<b>前にコンマ</b>がある。",
          [("My brother, <mark>who lives in Osaka</mark>, is a doctor.", "私の兄は大阪に住んでいて、医者をしている。"),
           ("He said nothing, <mark>which</mark> made her angry.", "彼は何も言わず、そのことが彼女を怒らせた。")],
          tip="先行詞に<b>あとから補足</b>する。「そして」「〜だが」と後ろに流して訳す。コンマがあると<b>先行詞は1つに決まっている</b>（兄は1人）。<b>, which は前の文全体</b>を受けることもある。",
          warn="非制限用法では <b>that は使えない</b>。"),
        i("md-what", "must", "関係代名詞 what（〜するもの・こと）",
          "<b>先行詞がなく</b>、後ろに何かが欠けている。名詞節をつくる。",
          [("<mark>What she said</mark> surprised everyone.", "彼女が言ったことは、皆を驚かせた。"),
           ("This is <mark>what I wanted</mark>.", "これが私がほしかったものだ。")],
          tip="<b>what ＝ the thing(s) which</b>。名詞節として S・O・C になる。「〜すること／もの」と訳す。"),
        i("md-that-what", "must", "that と what の見分け",
          "関係詞の前に<b>先行詞があるか</b>、後ろが<b>完全か欠けているか</b>。",
          table=(["形", "先行詞", "後ろ", "例"], [
              ["関係代名詞 that", "あり", "欠ける", "the thing <b>that</b> he wants"],
              ["接続詞 that", "（なし）", "完全", "I know <b>that</b> he wants it"],
              ["同格の that", "あり（fact / idea / belief など）", "完全", "the fact <b>that</b> he left（<a href=\"p-order.html#od-appositive\">同格</a>）"],
              ["関係代名詞 what", "なし（含む）", "欠ける", "I know <b>what</b> he wants"]]),
          tip="<b>What は「〜のもの」自体が先行詞</b>を含むので、前に名詞は置かない。後ろの形で迷ったら、「欠けている（→関係詞）」か「完全（→接続詞）」を先に判断する。"),
        i("md-compound-rel", "core", "複合関係詞（whatever / whoever / however など）",
          "wh- に <b>-ever</b> がついた語。名詞節と副詞節、両方の働きがある。",
          table=(["語", "名詞節（〜するものは何でも）", "副詞節（たとえ〜でも）"], [
              ["whatever", "何でも", "何が／何を〜しようと"],
              ["whoever", "だれでも", "だれが〜しようと"],
              ["whichever", "どちらでも", "どちらが〜しようと"],
              ["whenever / wherever", "〜するときはいつでも／〜するところはどこでも", "いつ／どこで〜しようと"],
              ["however ＋形容詞・副詞", "—", "どんなに〜でも"]]),
          ex=[("You can choose <mark>whatever you like</mark>.", "好きなものは何でも選べる。"),
           ("<mark>Whatever happens</mark>, I will support you.", "何が起ころうと、私はあなたを支持する。"),
           ("<mark>Whenever I see him</mark>, he is smiling.", "彼に会うときはいつも、彼は笑っている。")],
          tip="動詞の目的語や主語なら名詞節、<b>コンマで主節に続くなら副詞節（譲歩）</b>。譲歩の意味のときは、no matter ＋ wh- と言い換えられる。<b>whenever / wherever</b> は「〜するときはいつでも」の意味でもよく使う。"),
        i("md-chain-rel", "core", "連鎖関係詞節（who I think is 〜）",
          "関係詞の直後に、<b>I think / he said / we believe</b> のような S＋V が割り込んでいる。",
          [("He is the man <mark>who</mark> <u>I think</u> <mark>is the best candidate</mark>.", "彼は、私が最も適任だと思う男性だ。"),
           ("The idea <mark>that</mark> <u>I thought</u> <mark>was impossible</mark> turned out to work.", "私が不可能だと思っていた案は、うまくいくことがわかった。")],
          tip="<b>I think / I thought を外して読む</b>。関係詞（who）は、外した後ろの動詞（is）の主語になる。挿入と同じ処理。",
          warn="主格なので <b>who</b>。× the man <b>whom</b> I think is honest は誤り（I think を外して考える）。"),
        i("md-quasi-rel", "skip", "疑似関係代名詞（as / than / but）",
          "<b>such A as 〜</b>、<b>the same A as 〜</b>、<b>as</b> が関係代名詞のように働く形。",
          line="出題は稀。<b>such A as 〜 ＝ 〜のようなA</b>、<b>the same A as 〜 ＝ 〜と同じA</b>として読めれば十分。<b>as is often the case（よくあることだが）</b>のような慣用句も、そのまま覚える。"),
    ]),
    ("後置修飾・名詞まわり", [
        i("md-participle-post", "must", "分詞の後置修飾",
          "名詞のすぐ後ろに <b>-ing / p.p.＋語句</b>。",
          [("The boy <mark>standing there</mark> is my brother.", "そこに立っている少年は私の弟だ。"),
           ("The language <mark>spoken in Brazil</mark> is Portuguese.", "ブラジルで話されている言語はポルトガル語だ。")],
          tip="<b>関係詞＋be の省略</b>と考える。名詞との関係が<b>「する」なら -ing、「される」なら p.p.</b>。"),
        i("md-adj-post", "core", "形容詞の後置修飾",
          "形容詞が<b>名詞の後ろ</b>に来ている。",
          [("I want <mark>something cold</mark> to drink.", "何か冷たい飲み物がほしい。"),
           ("There is <mark>nothing important</mark> in this document.", "この書類には重要なことは何もない。"),
           ("This is the best solution <mark>possible</mark>.", "これは可能な限り最善の解決策だ。")],
          tip="<b>-thing / -one / -body ＋形容詞</b>、<b>最上級・only ＋ -able / -ible の形容詞</b>は、後ろに置くこともある（the best possible solution のように前に置く形も普通）。形容詞に語句が付くと（a man kind to everyone）後置される。"),
        i("md-to-adj", "core", "名詞を説明する to 不定詞（the first ... to do など）",
          "名詞のあとに <b>to 不定詞</b>。名詞との関係を確かめる。",
          [("She was <mark>the first woman to win</mark> the prize.", "彼女は、その賞を取った最初の女性だった。"),
           ("He is <mark>the last person to tell</mark> a lie.", "彼は決して嘘をつくような人ではない。"),
           ("I have <mark>no chance to see</mark> him.", "私は彼に会う機会がない。"),
           ("I need <mark>a house to live in</mark>.", "私は住む家が必要だ。")],
          tip="<b>the last ... to do ＝ 「最も〜しそうにない（決して〜しない）」</b>。<b>the first / second / only ... to do</b> は、名詞が不定詞の意味上の主語。ability / chance / way などは同格的に説明する。<b>a house to live in / someone to talk with</b> のように、前置詞が後ろに残る形にも注意。"),
        i("md-prep-phrase", "must", "前置詞句が、どこにかかるか",
          "前置詞句（of 〜 / in 〜 / with 〜）が、<b>名詞</b>と<b>動詞</b>のどちらを修飾するか。",
          [("He saw the man <mark>with a telescope</mark>.", "彼は望遠鏡を持った男を見た。／彼は望遠鏡で男を見た。（2通りに読める）"),
           ("The results <mark>of the study</mark> <mark>on sleep</mark> <mark>in older adults</mark> were surprising.", "高齢者の睡眠に関する研究の結果は、驚くべきものだった。")],
          tip="基本は<b>直前の名詞にかかる</b>が、意味が通らなければ動詞にかかる。<b>前置詞句が連続</b>するときは、それぞれ<b>すぐ前の名詞</b>を修飾していくことが多い。"),
        i("md-noun-construction", "core", "名詞構文（名詞を動詞に戻して訳す）",
          "動詞から作られた名詞（destruction, arrival, decision など）が主語になっている。",
          [("<mark>His arrival</mark> surprised us.", "彼が到着したことが、私たちを驚かせた。→ 彼が着いたので、私たちは驚いた。"),
           ("<mark>The destruction of the city by the enemy</mark> shocked the world.", "敵が街を破壊したことが、世界に衝撃を与えた。")],
          tip="名詞を<b>動詞に戻し</b>て訳す。<b>他動詞から作られた名詞</b>（destruction など）では of ＝ 目的語、by ＝ 主語。<b>自動詞から作られた名詞</b>（arrival, growth など）では of ＝ 主語（the arrival of the train ＝ 列車が到着すること）。無生物主語の文と同じく、副詞的に訳すと自然になる。"),
    ]),
    ],
    quiz=[
        ("（　）に入る語を答えなさい。<br><i>The woman (　　　) I spoke to is my aunt.</i>　ア. whose　イ. whom（who / that も可）",
         "<p><b class=\"a\">イ. whom</b></p><p>人が先行詞で、spoke to の目的語（人）が欠けている。that や who、省略も可。</p>"),
        ("次の文を訳しなさい。<br><i>Whenever I visit him, he is cooking.</i>",
         "<p><b class=\"a\">彼を訪ねるときはいつも、彼は料理をしている。</b></p><p>whenever ＝ 〜するときはいつでも。</p>"),
        ("次の文を訳しなさい。<br><i>She is the last person to betray her friends.</i>",
         "<p><b class=\"a\">彼女は決して友人を裏切るような人ではない。</b></p><p>the last ... to do ＝ 最も〜しそうにない。</p>"),
        ("what と that のどちらが入るか。<br><i>This is (　　　) I have been looking for.</i>",
         "<p><b class=\"a\">what</b></p><p>先行詞がなく、looking for の目的語が欠けている。「これが私が探していたものだ」。</p>"),
    ],
)
