from content.base import i

PAGE = dict(
    file="p-negation.html", key="ng", name="否定",
    icon="🚫",
    summary="全否定・部分否定、準否定、二重否定、否定を含む慣用表現、否定の転移と範囲。",
    lead="否定は、見落とすと意味が正反対になる。「どこまでが否定されているか」と「隠れた否定」を見抜く。",
    sections=[
    ("基本の否定", [
        i("ng-partial", "must", "全否定と部分否定",
          "<b>not</b> と <b>all / every / always / both / necessarily</b> が一緒に出ている。",
          table=(["全否定（まったく〜ない）", "部分否定（すべてが〜とは限らない）"], [
              ["none / nothing / no one / never / neither", "not all / not every / not always / not both / not necessarily / not completely"]]),
          ex=[("<mark>Not all</mark> students like math.", "すべての学生が数学を好きなわけではない。"),
           ("Difficult words are <mark>not always</mark> important.", "難しい単語がいつも重要とは限らない。")],
          tip="<b>not ＋ 全部を表す語 ＝ 部分否定</b>（「〜でないものもある」）。全否定は、<b>none / never / neither</b> を使う。"),
        i("ng-not-a-but-b", "must", "not A but B / not only A but also B",
          "A と B は、<b>同じ形</b>。強調したいのは B。",
          ex=[("The goal is <mark>not to memorize rules but to use them</mark>.", "目標はルールを暗記することではなく、それを使うことだ。"),
           ("She is <mark>not only</mark> smart <mark>but also</mark> kind.", "彼女は賢いだけでなく、親切でもある。")],
          tip="<b>not A but B ＝ AではなくB</b>。<b>not only A but also B ＝ AだけでなくBも</b>（Bに重み）。"),
        i("ng-semi", "must", "準否定（hardly / scarcely / rarely / seldom / few / little）",
          "形は肯定でも、意味が<b>「ほとんど〜ない」「めったに〜ない」</b>。",
          ex=[("There was <mark>hardly</mark> anyone in the room.", "部屋にはほとんどだれもいなかった。"),
           ("I have <mark>few</mark> friends here.", "ここには友だちがほとんどいない。"),
           ("I have <mark>a few</mark> friends here.", "ここには友だちが少しはいる。")],
          tip="<b>hardly / scarcely ＝ 程度（ほとんど〜ない）</b>、<b>rarely / seldom ＝ 頻度（めったに〜ない）</b>、<b>few ＝ 数</b>、<b>little ＝ 量</b>がほとんどない（否定的）。<b>a few / a little ＝ 少しある</b>（肯定的）。<b>only a few ＝ ほとんどない</b>、<b>quite a few ＝ かなり多い</b>。",
          warn="hardly / scarcely と not は<b>併用しない</b>（× not hardly）。"),
        i("ng-no-noun", "must", "no ＋名詞（1つも〜ない）",
          "名詞の前の <b>no</b> は、<b>not any</b> の意味。",
          ex=[("I have <mark>no time</mark>.", "私には時間がまったくない。"),
           ("<mark>No student</mark> came to the party.", "パーティーに来た学生は1人もいなかった。"),
           ("He is <mark>no fool</mark>.", "彼は決して愚か者ではない。")],
          tip="<b>no ＋ 名詞 ＝ 少しも〜ない</b>。主語にあれば「〜する人は誰も…ない」。<b>be no ＋ 名詞</b>は、強い否定（決して〜ではない）。"),
        i("ng-no-longer", "core", "no longer / not ... any longer / no more",
          "<b>もはや〜ない</b>を表す表現。",
          ex=[("He <mark>no longer</mark> lives here.", "彼はもうここには住んでいない。"),
           ("I can't wait <mark>any longer</mark>.", "私はこれ以上待てない。")],
          tip="<b>no longer ＝ not ... any longer ＝ もはや〜ない</b>（時間）。<b>no more</b> は、程度や数量の「もう〜ない」にも使う。"),
        i("ng-strong", "core", "強い否定の副詞句（not at all / not in the least など）",
          "<b>少しも〜ない</b>を表す表現。",
          ex=[("I'm <mark>not in the least</mark> tired.", "私は少しも疲れていない。"),
           ("There was <mark>not a single</mark> mistake.", "間違いは1つもなかった。")],
          tip="<b>not at all / not a bit / not in the least / not a single 〜 ＝ 少しも〜ない</b>。"),
    ]),
    ("見落としやすい否定", [
        i("ng-double", "core", "二重否定（否定＋否定＝強い肯定）",
          "<b>否定語が2つ</b>出ている。",
          ex=[("I <mark>never</mark> see this picture <mark>without</mark> thinking of my mother.", "この絵を見ると、必ず母を思い出す。"),
           ("There is <mark>no</mark> rule <mark>without</mark> exceptions.", "例外のない規則はない。"),
           ("It is <mark>not impossible</mark>.", "不可能ではない。（可能かもしれない）")],
          tip="<b>never ... without -ing ＝ 〜すると必ず…する</b>、<b>no ... without ~ ＝ 〜のない…はない</b>。否定を2回打ち消して、肯定に読み替える。"),
        i("ng-idioms", "core", "否定を含む慣用表現",
          "形と意味が<b>ずれている</b>ので、まとめて覚える。",
          table=(["表現", "意味"], [
              ["nothing but 〜", "〜だけ（＝ only）"],
              ["anything but 〜", "決して〜ではない"],
              ["all but 〜", "ほとんど〜（＝ almost）"],
              ["far from 〜", "決して〜ではない"],
              ["free from / free of 〜", "〜がない"],
              ["by no means 〜", "決して〜ない"],
              ["none other than 〜", "他ならぬ〜"],
              ["cannot ... too 〜", "いくら〜してもしすぎない"]]),
          ex=[("He is <mark>anything but</mark> a fool.", "彼は決して愚か者ではない。"),
           ("The work is <mark>far from</mark> finished.", "その仕事は少しも終わっていない。"),
           ("You <mark>cannot</mark> be <mark>too</mark> careful.", "いくら注意してもしすぎることはない。")],
          warn="<b>nothing but（〜だけ）</b> と <b>anything but（決して〜ない）</b> は、逆の方向。"),
        i("ng-hidden", "core", "否定の意味を含む語（fail / refuse / beyond など）",
          "<b>not がなくても</b>、意味が否定になる語句。",
          table=(["語句", "意味"], [
              ["fail to do", "〜しない・〜できない"],
              ["refuse / deny", "拒否する・否定する"],
              ["lack / absent", "欠けている・いない"],
              ["too ... to do", "〜すぎて…できない"],
              ["beyond 〜", "〜の及ばない：beyond my understanding（理解できない）"],
              ["above 〜", "〜しないような：above telling lies（嘘をつくようなことはしない）"],
              ["but for 〜 / without 〜", "〜がなければ"]]),
          ex=[("The idea is <mark>beyond</mark> my understanding.", "その考えは、私には理解できない。")],
          tip="肯定文の形でも、<b>意味は否定</b>。訳すときに否定の形に直す。"),
        i("ng-transfer", "core", "否定の転移（I don't think ~）",
          "<b>think / believe / suppose / expect ＋ that 節</b>の否定。",
          ex=[("I <mark>don't think</mark> he is honest.", "彼は正直ではないと思う。")],
          tip="日本語の直訳（思わない）ではなく、<b>「〜でないと思う」</b>と、that 節の中を否定して訳す。not は that 節の内容を否定している。"),
        i("ng-scope", "core", "否定の範囲（not ... because 〜）",
          "<b>not</b> が<b>どこまで</b>を否定しているか。",
          ex=[("I did <mark>not</mark> leave <mark>because I was angry</mark>.", "怒ったから出たのではない。（理由を否定）"),
           ("He did not come, <mark>because</mark> he was ill.", "彼は病気だったので、来なかった。（コンマで区切ると、理由を述べる）")],
          tip="<b>not ... because 〜</b> は、「〜だから…したのではない」（理由の否定）と、「〜だから…しなかった」の両方に読める。<b>コンマ・文脈・後ろの but</b> で決める。"),
        i("ng-emphatic", "core", "否定副詞句が文頭に出る倒置（on no account / by no means など）",
          "文頭の <b>at no time / on no account / under no circumstances / in no way</b>。",
          ex=[("<mark>On no account should</mark> you open this door.", "決してこのドアを開けてはならない。"),
           ("<mark>Under no circumstances will</mark> I agree.", "どんな場合でも、私は同意しない。")],
          tip="<b>否定語句が文頭に出ると、倒置</b>（助動詞 ＋ S ＋ V）になる。「決して〜ない」と強く訳す。"),
        i("ng-question", "skip", "否定疑問文・付加疑問文",
          "<b>Don't you 〜?</b> や、文末の <b>..., don't you?</b>。",
          line="読解の得点には直結しにくい。<b>否定疑問文は「〜ではないのですか」</b>、答え方が日本語と逆になる（yes/no は、答えの内容が肯定か否定かで決まる）と知っていれば十分。"),
    ]),
    ],
    quiz=[
        ("次の文を訳しなさい。<br><i>Not all students like math.</i>",
         "<p><b class=\"a\">すべての学生が数学を好きなわけではない。</b></p><p>not ＋ all は部分否定。</p>"),
        ("次の文の意味を答えなさい。<br><i>He is anything but a fool.</i>",
         "<p><b class=\"a\">彼は決して愚か者ではない。</b></p><p>anything but ＝ 決して〜ではない。nothing but（〜だけ）と混同しない。</p>"),
        ("次の文を訳しなさい。<br><i>I never see this picture without thinking of my mother.</i>",
         "<p><b class=\"a\">この絵を見ると、いつも母を思い出す。</b></p><p>never ... without -ing ＝ 〜すると必ず…する（二重否定）。</p>"),
        ("few と a few の違いを、例文で答えなさい。<br><i>I have few friends. ／ I have a few friends.</i>",
         "<p><b class=\"a\">前者：友だちがほとんどいない ／ 後者：友だちが少しはいる</b></p><p>a がつくと肯定的（少しある）、つかないと否定的（ほとんどない）。</p>"),
    ],
)
