from content.base import i

PAGE = dict(
    file="p-order.html", key="od", name="語順・特殊な構造",
    icon="🔀",
    summary="主語の見つけ方、挿入、同格、倒置、省略、強調など、語順が普通と違う文。",
    lead="英文の語順が「いつもの形」と違うとき、何が起きているかを見抜く。倒置・省略・挿入・同格が読めれば、長い文も骨組みが取れる。",
    sections=[
    ("主語・目的語をつかむ", [
        i("od-long-subject", "must", "主語が長い（節が主語になる）",
          "動詞の直前までが、主語のかたまり。",
          [("<mark>What matters most in reading</mark> is knowing where the sentence ends.", "読解でいちばん大切なのは、文がどこで終わるかを知ることだ。")],
          tip="What / How / That などで始まる節が文頭に来たら、<b>その節が丸ごと主語</b>。節の終わりは、<b>次に来る動詞（is）の直前</b>。"),
        i("od-insertion", "must", "挿入で主語と動詞が離れている",
          "コンマ2つ・ダッシュ2本・カッコではさまれた部分を外す。",
          [("The results, <mark>as the authors admit</mark>, are still uncertain.", "その結果は、著者たちも認めているように、まだ確かではない。")],
          tip="はさまれた部分を外して<b>S＋V を先に確定</b>。挿入の内容は、あとから足す。"),
        i("od-dummy-object", "must", "形式目的語 it（find / make it 〜 to do）",
          "find / make / think / consider の直後に <b>it ＋形容詞・名詞</b>が来たら、it は後ろの to 不定詞・that 節の代わり。",
          [("I found <mark>it</mark> difficult <mark>to answer the question quickly</mark>.", "その質問にすばやく答えるのは難しいとわかった。"),
           ("Modern technology makes <mark>it</mark> possible <mark>for us to work from home</mark>.", "現代の技術のおかげで、私たちは在宅で働くことができる。")],
          tip="it は訳さなくてよい。<b>「to 以下（真の目的語）が C だと思う／わかる」</b>と、後ろから訳す。SVOC の O が it、C が形容詞・名詞。"),
        i("od-wh-to", "must", "疑問詞＋to 不定詞と、間接疑問の語順",
          "what / where / how / when ＋ to do は「〜すべきか」。疑問詞の後ろが S V の語順なら間接疑問。",
          [("I don't know <mark>what to do</mark> next.", "次に何をすべきかわからない。"),
           ("Tell me <mark>where he lives</mark>.", "彼がどこに住んでいるか教えて。")],
          tip="間接疑問は<b>疑問詞＋S＋V の語順</b>（疑問文の語順にならない）。全体で名詞節として、動詞の目的語などになる。",
          warn="× Tell me where does he live. は誤り。Do you know where he lives? のように、文全体が疑問文でも、間接疑問の部分は S V の語順。"),
        i("od-appositive", "must", "同格（名詞を言い換える・説明する）",
          "名詞のあとに、その名詞と「イコール」の関係の語句が来ていないか。",
          table=(["形", "例", "訳"], [
              ["名詞＋that 節", "the fact <b>that he left</b>", "彼が去ったという事実"],
              ["名詞＋of ＋動名詞", "the habit <b>of getting up early</b>", "早起きの習慣"],
              ["名詞, 名詞,", "Tokyo, <b>the capital of Japan</b>,", "日本の首都である東京"],
              ["名詞＋: / ―", "one goal: <b>to win</b>", "1つの目標、つまり勝つこと"],
              ["the city of 〜", "the city <b>of Kyoto</b>", "京都という都市"]]),
          tip="同格の that 節が続く名詞は決まっている：<b>fact, idea, belief, news, rumor, hope, possibility, evidence, claim</b> など。that の後ろが<b>完全な文</b>なら同格。"),
    ]),
    ("倒置（V が S の前に出る）", [
        i("od-neg-inversion", "core", "否定語が文頭に出る倒置",
          "文頭に <b>Never / Hardly / Scarcely / Rarely / Seldom / Little / Not only / No sooner / Nowhere</b>。",
          [("<mark>Never have I</mark> seen such a beautiful sunset.", "こんなに美しい夕焼けは見たことがない。"),
           ("<mark>Not only did she</mark> pass the exam, but she also got the top score.", "彼女は試験に合格しただけでなく、最高点も取った。"),
           ("<mark>Little did he</mark> know that his life was about to change.", "彼は、自分の人生がまもなく変わるとは夢にも思わなかった。")],
          tip="倒置＝<b>疑問文の語順</b>（助動詞／be ＋ S ＋ 動詞）。訳は普通の語順に戻して、否定語の意味を強める。",
          warn="Not only A but also B では、倒置するのは<b>Not only が文頭に来た側の節だけ</b>。but also 以下は普通の語順。"),
        i("od-only", "core", "Only ＋副詞（句・節）が文頭の倒置",
          "文頭の <b>Only ＋ 副詞（句・節）</b>のあとが、疑問文の語順になる。",
          [("<mark>Only when I moved abroad did I realize</mark> how much I depended on my family.", "海外に引っ越して初めて、私はいかに家族に頼っていたかに気づいた。"),
           ("<mark>Only in this way can we</mark> solve the problem.", "この方法でしか、私たちはその問題を解決できない。")],
          tip="<b>「〜して初めて…」「〜でしか…ない」</b>と訳す。only の後ろの副詞（句・節）が、倒置の合図。",
          warn="Only ＋ <b>主語</b>のときは倒置しない：Only Tom knew the answer.（トムだけが答えを知っていた）。"),
        i("od-so-neither", "must", "So do I / Neither do I（Sもそうだ）",
          "会話文やその一部に、<b>So ＋ 助動詞 ＋ S</b>／<b>Neither ＋ 助動詞 ＋ S</b>。",
          [("“I like coffee.” “<mark>So do I</mark>.”", "「コーヒーが好きだ」「私もそうだ」"),
           ("“I can't swim.” “<mark>Neither can I</mark>.”", "「泳げない」「私もだ」")],
          tip="肯定なら <b>So ＋助動詞＋S</b>、否定なら <b>Neither / Nor ＋助動詞＋S</b>。助動詞は前の文の動詞に合わせる（like → do、can't → can）。",
          warn="<i>So I do.</i>（語順は S V）は「本当にそうだ」と、相手の発言を確認する別の意味。"),
        i("od-c-inversion", "core", "補語・場所を表す語句の倒置",
          "文頭に<b>補語や場所・方向の副詞（句）</b>があり、動詞が主語の前にある。",
          [("<mark>Here comes</mark> the bus.", "ほら、バスが来た。"),
           ("<mark>Happy are</mark> those who can find joy in small things.", "小さなことに喜びを見いだせる人は幸せだ。"),
           ("<mark>On the hill stands</mark> an old church.", "丘の上に古い教会が建っている。")],
          tip="<b>主語は動詞のあと</b>にある。動詞の形は、後ろの主語に合わせる（stands ← an old church）。",
          warn="主語が代名詞のときは倒置しない：Here <b>it</b> comes."),
        i("od-concessive-inv", "core", "譲歩の倒置（形容詞・名詞・副詞・動詞＋as＋S＋V）",
          "<b>形容詞・名詞・副詞・動詞の原形が as / though の前に出ている</b>形。",
          [("<mark>Young as he was</mark>, he led the team.", "彼は若かったけれども、チームを率いた。"),
           ("<mark>Try as he might</mark>, he could not open the door.", "どんなに頑張っても、彼はドアを開けられなかった。")],
          tip="<b>「〜だけれども」</b>と訳す。本来の語順は Although he was young。名詞のときは冠詞が消える（Child as he was, 〜）。"),
    ]),
    ("強調・省略・慣用", [
        i("od-cleft", "must", "強調構文（It is A that 〜）",
          "<b>It is ＋ 強調したい語句 ＋ that ＋ 欠けた文</b>。強調された語句を元の位置に戻せるか。",
          ex=[("<mark>It was the teacher that</mark> solved the problem.", "その問題を解いたのは、先生だった。"),
              ("<mark>It is in the morning that</mark> I study best.", "私がいちばんよく勉強するのは、朝だ。"),
              ("<mark>It was because of the rain that</mark> the game was canceled.", "試合が中止になったのは、雨のためだった。")],
          tip="<b>強調された語句を、that 以下の文の元の位置に戻すと、完全な文になる</b>のが強調構文（The teacher solved the problem.）。強調できるのは、主語・目的語・副詞（句・節）。「〜なのは…だ」と訳す。",
          warn="形式主語の <b>It is 形容詞 that S V</b>（It is true that he left.）は、that 以下が<b>それだけで完全な文</b>で、戻す語句がない。<a href=\"p-clause.html#cl-not-until\">It is not until ... that 〜</a> も強調構文の形。"),
        i("od-emphasis", "core", "強調の do・very・再帰代名詞",
          "動詞の前の <b>do / does / did</b>、名詞の前の <b>the very</b>、名詞の直後または文末の <b>-self</b>。",
          [("He <mark>did</mark> say so.", "彼は確かにそう言った。"),
           ("This is <mark>the very</mark> book I was looking for.", "これこそ私が探していた本だ。"),
           ("She did it <mark>herself</mark>.", "彼女は自分でそれをやった。")],
          tip="肯定文の <b>do ＋ 原形</b>は「確かに〜」。後ろの動詞は原形で、時制は do に出る。-self を取っても文は成り立つ。"),
        i("od-rhetorical", "core", "修辞疑問文（疑問文の形で、反対の意味を言う）",
          "答えを求めていない疑問文。<b>Who knows 〜? / What is the use of 〜?</b>",
          [("<mark>Who knows</mark> what will happen tomorrow?", "明日何が起こるか、だれにもわからない。"),
           ("<mark>What is the use of</mark> worrying?", "心配して何になるだろうか（何にもならない）。")],
          tip="<b>Who knows 〜? ＝ Nobody knows 〜</b>。「〜だろうか、いや〜ない」と、否定の断定に読む。Who can ... ? も同じ。"),
        i("od-what-idioms", "core", "what を使う慣用表現",
          "what が、疑問詞・関係詞の意味ではなく、<b>決まり文句</b>として出てくる。",
          table=(["表現", "意味", "例"], [
              ["what is called / what we call", "いわゆる", "He is what is called a bookworm."],
              ["what is more / what is worse", "その上／さらに悪いことに", "What is worse, it began to rain."],
              ["what S is / what S was", "Sの人柄（現在・過去の姿）", "She is not what she was ten years ago."],
              ["what S has", "Sの財産", "You should not judge people by what they have."],
              ["what with A and (what with) B", "AやBのせいで", "What with the rain and the cold, I stayed home."],
              ["A is to B what C is to D", "AのBに対する関係は、CのDに対する関係と同じ", "Reading is to the mind what food is to the body."]]),
          tip="表全体を「かたまり」として覚える。最後の型は、<b>読書：精神＝食べ物：体</b>のように、比率の関係で訳す。"),
        i("od-common-ellipsis", "core", "共通する語句の省略",
          "前と同じ語句（動詞など）が、後ろでは<b>省かれている</b>。",
          [("Some people prefer tea, <mark>while others (prefer)</mark> coffee.", "紅茶が好きな人もいれば、コーヒーが好きな人もいる。"),
           ("Tom likes tennis, and Mary (likes) golf.", "トムはテニスが好きで、メアリーはゴルフが好きだ。")],
          tip="コンマで区切られて動詞がない側は、<b>前の動詞を補って読む</b>。and / but / while のあとに多い。"),
        i("od-literary", "skip", "文語的な倒置（Such is life / So great was 〜）",
          "<b>Such is life.</b>／<b>So great was his surprise that 〜.</b> など、格式のある文章で使われる倒置。",
          line="出題は少ない。出会ったら、<b>「Such is 〜＝それは〜だ」「So 形容詞 was S that 〜＝Sはとても〜だったので…」</b>と、通常の語順に戻して読めれば十分。"),
    ]),
    ],
    quiz=[
        ("次の文を訳しなさい。<br><i>Rarely do we see such honesty these days.</i>",
         "<p><b class=\"a\">最近、これほどの正直さはめったに見られない。</b></p><p>否定語 Rarely が文頭に出て、do we see と倒置している。</p>"),
        ("（　）に入る語を答えなさい。<br><i>“I don't like fish.” “(　　　) do I.”</i>",
         "<p><b class=\"a\">Neither（または Nor）</b></p><p>否定文への「私もだ」は Neither ＋ 助動詞 ＋ S。前の文の動詞が like なので、助動詞は do。</p>"),
        ("次の文を訳しなさい。<br><i>Only by working together can we solve this problem.</i>",
         "<p><b class=\"a\">協力することによってのみ、私たちはこの問題を解決できる。</b></p><p>Only ＋ 副詞句が文頭で、can we solve と倒置している。</p>"),
        ("it の中身を答えなさい。<br><i>She made it clear that she would not attend.</i>",
         "<p><b class=\"a\">that she would not attend</b></p><p>形式目的語の it。「彼女は出席しないことを明らかにした」。</p>"),
        ("強調構文か形式主語か答えなさい。<br><i>It was in 1990 that the company was founded.</i>",
         "<p><b class=\"a\">強調構文</b></p><p>in 1990 を元の位置に戻すと、The company was founded in 1990. と完全な文になる。「その会社が設立されたのは1990年だ」。</p>"),
    ],
)
