from content.base import i

PAGE = dict(
    file="p-subjunctive.html", key="sj", name="仮定法・助動詞",
    icon="💭",
    summary="仮定法過去・過去完了、if の省略、wish、as if、without、助動詞の推量、used to。",
    lead="仮定法は「動詞の形が、実際の時間とずれている」ことが目印。ずれに気づけば、現実と違う話だとわかる。",
    sections=[
    ("仮定法", [
        i("sj-past", "must", "仮定法過去（現在の事実に反する仮定）",
          "<b>If S 過去形, S would / could / might ＋ 原形</b>。",
          ex=[("<mark>If I were you</mark>, I <mark>would accept</mark> the offer.", "もし私があなたなら、その申し出を受けるだろう。"),
           ("<mark>If I had</mark> more time, I <mark>would read</mark> more.", "もっと時間があれば、もっと読むのだが。")],
          tip="<b>動詞は過去形なのに、意味は「今」</b>。そこが仮定法のサイン。be 動詞は主語にかかわらず <b>were</b>（口語では was も使うが、入試では were）。「〜なら…だろうに」と訳す。"),
        i("sj-past-perf", "must", "仮定法過去完了（過去の事実に反する仮定）",
          "<b>If S had p.p., S would / could / might have p.p.</b>",
          ex=[("<mark>If I had studied</mark> harder, I <mark>would have passed</mark> the exam.", "もっと勉強していれば、試験に合格していたのに。"),
           ("<mark>If he had left</mark> earlier, he <mark>could have caught</mark> the train.", "もっと早く出ていれば、彼はその電車に間に合ったのに。")],
          tip="<b>過去についての反対の仮定</b>。「〜だったら…だっただろうに」と訳す。実際は「勉強しなかったので不合格だった」という意味。"),
        i("sj-mixed", "core", "混合型（過去の仮定が今の結果につながる）",
          "<b>If S had p.p., S would ＋ 原形（now）</b> のように、前半と後半で時制が違う。",
          ex=[("If I <mark>had taken</mark> the medicine, I <mark>would be</mark> well now.", "薬を飲んでいたら、今は元気なのに。")],
          line="出題は稀。前半が<b>過去</b>、後半が<b>今</b>に、それぞれ反対の仮定になっている、と読めれば十分。"),
        i("sj-were-to-should", "core", "未来についての仮定（If S should / If S were to）",
          "<b>If S should ＋ 原形</b>（万一）、<b>If S were to ＋ 原形</b>（仮に）。",
          ex=[("<mark>If it should rain</mark> tomorrow, the game will be postponed.", "万一明日雨が降ったら、試合は延期される。"),
           ("<mark>If the sun were to disappear</mark>, life would end.", "もし太陽が消えるとしたら、生命は終わるだろう。")],
          tip="<b>should ＝ 万一</b>（実現の可能性は低いが、ありうる）。<b>were to ＝ 仮に〜だとしたら</b>（実現の可能性を問わず、仮の話として述べる。ありえないことにも使える）。"),
        i("sj-inversion", "core", "if の省略と倒置（Were / Had / Should が文頭）",
          "文頭が <b>Were / Had / Should ＋ S</b>。",
          ex=[("<mark>Had I known</mark> the truth, I would have told you.", "真実を知っていたら、あなたに話したのに。（＝ If I had known）"),
           ("<mark>Were I</mark> in your position, I would accept the offer.", "私があなたの立場なら、その申し出を受ける。"),
           ("<mark>Should you need</mark> any help, please call me.", "万一助けが必要なら、電話をください。")],
          tip="<b>if を省略すると、助動詞が S の前に出る</b>。<b>Were I 〜 ＝ If I were 〜</b>、<b>Had I p.p. ＝ If I had p.p.</b>、<b>Should S ＝ If S should</b>。"),
        i("sj-wish", "must", "I wish ＋ 仮定法（〜ならいいのに）",
          "<b>I wish ＋ S ＋ 過去形／過去完了／would</b>。",
          ex=[("I wish <mark>I were</mark> taller.", "もっと背が高ければいいのに。（今の願望）"),
           ("I wish <mark>I had studied</mark> harder.", "もっと勉強しておけばよかった。（過去への後悔）"),
           ("<mark>If only</mark> I had more time!", "もっと時間があればなあ。")],
          tip="<b>wish ＋ 過去形 ＝ 今の願望</b>、<b>wish ＋ had p.p. ＝ 過去への後悔</b>。<b>If only 〜! ＝ 〜でありさえすれば</b>（願望）。"),
        i("sj-as-if", "core", "as if / as though ＋ 仮定法",
          "<b>まるで〜であるかのように</b>。",
          ex=[("She talks <mark>as if she knew</mark> everything.", "彼女はまるで何でも知っているかのように話す。"),
           ("He looked <mark>as if he had seen</mark> a ghost.", "彼はまるで幽霊を見たかのような顔をしていた。")],
          tip="<b>主節と同じ時点なら過去形、主節より前なら had p.p.</b>。事実として実際にそう見えるときは、<b>直説法</b>（It looks as if it is going to rain.）も使う。"),
        i("sj-high-time", "core", "It is (high) time ＋ S ＋ 過去形",
          "<b>It is time ＋ 過去形</b>。",
          ex=[("<mark>It is time you went</mark> to bed.", "もう寝る時間ですよ（とっくに寝ているべき時間だ）。")],
          tip="<b>「もう〜すべき時だ」</b>（high time だと「とっくに」の気持ちが強まる）。動詞は過去形だが、意味は今。<b>It is time to do</b>／<b>It is time for A to do</b> は同じ形で言えるが、過去形を使うと<b>催促・非難の含み</b>が出る。"),
        i("sj-would-rather", "core", "would rather ＋ S ＋ 過去形",
          "<b>would rather ＋ 原形</b>（自分の希望）と、<b>would rather ＋ S ＋ 過去形</b>（人への希望）。",
          ex=[("I <mark>would rather</mark> stay home.", "私は家にいるほうがよい。"),
           ("I <mark>would rather</mark> you <mark>stayed</mark> here.", "あなたにはここにいてほしい。")],
          tip="主語が同じなら原形、<b>主語が違うなら過去形</b>（仮定法過去）。<b>would rather A than B ＝ BよりむしろA</b>。"),
        i("sj-without", "must", "without / but for / If it were not for（〜がなければ）",
          "<b>名詞句</b>が「もしも〜がなければ」の意味を表す。",
          ex=[("<mark>Without</mark> your help, I <mark>could not have finished</mark> it.", "あなたの助けがなければ、私はそれを終えられなかっただろう。"),
           ("<mark>But for</mark> the rain, we <mark>would have had</mark> a picnic.", "雨がなければ、私たちはピクニックをしていただろう。"),
           ("<mark>If it were not for</mark> water, nothing could live.", "水がなければ、何も生きられないだろう。")],
          tip="<b>without ＝ but for ＝ If it were not for（現在）／If it had not been for（過去）</b>。主節の <b>would / could（＋have p.p.）</b>が、仮定法のサイン。"),
        i("sj-otherwise", "core", "otherwise / or else（さもなければ）",
          "<b>otherwise</b> が、前の内容の反対を仮定している。",
          ex=[("I was busy; <mark>otherwise</mark> I <mark>would have come</mark>.", "私は忙しかった。そうでなければ、行っていたのに。")],
          tip="<b>otherwise ＝ if ... not の内容</b>を含む。後ろに <b>would / could</b> があれば、仮定法。"),
        i("sj-hidden-cond", "core", "条件が隠れている仮定法",
          "<b>if がない</b>のに、<b>would / could</b> が使われている。",
          ex=[("<mark>A wise person</mark> would not say such a thing.", "賢い人なら、そんなことは言わないだろう。"),
           ("<mark>To hear him speak</mark>, you would think he was a native.", "彼が話すのを聞けば、母語話者だと思うだろう。"),
           ("<mark>With more effort</mark>, he could have succeeded.", "もっと努力していれば、彼は成功できただろうに。")],
          tip="<b>主語・to 不定詞・分詞・with 〜・副詞句</b>が、条件（もし〜なら）を含んでいる。<b>would / could の出現が合図</b>。"),
    ]),
    ("助動詞", [
        i("sj-modal-basic", "must", "助動詞の基本と、推量の度合い",
          "助動詞は、<b>どのくらい確かか</b>を表す。",
          table=(["助動詞", "意味（推量）"], [
              ["must be 〜", "〜にちがいない（確信）"],
              ["will / would be 〜", "〜だろう"],
              ["should / ought to be 〜", "〜のはずだ"],
              ["may / might be 〜", "〜かもしれない"],
              ["can be 〜", "〜でありうる"],
              ["cannot be 〜", "〜のはずがない"]]),
          ex=[("He <mark>must be</mark> tired after such a long trip.", "そんな長旅のあとで、彼は疲れているにちがいない。"),
           ("That <mark>cannot be</mark> true.", "それは本当のはずがない。")],
          tip="<b>must be ＝ 確信、cannot be ＝ ありえない</b>。過去についての推量は、<a href=\"grammar.html#modal-perfect\">助動詞＋have p.p.</a>。"),
        i("sj-may-well", "core", "may well / may as well / cannot help -ing",
          "助動詞を含む慣用表現。",
          ex=[("You <mark>may well</mark> be proud of your son.", "あなたが息子さんを誇りに思うのももっともだ。"),
           ("You <mark>may as well</mark> try.", "やってみたほうがいい（やってもいいだろう）。"),
           ("I <mark>cannot help laughing</mark>.", "私は笑わずにはいられない。")],
          tip="<b>may well do ＝ 〜するのももっともだ／おそらく〜だろう</b>、<b>may as well do ＝ 〜したほうがいい</b>（消極的な提案）。<b>cannot help -ing ＝ cannot help but do ＝ cannot but do ＝ 〜せずにはいられない</b>。"),
        i("sj-used-to", "must", "used to / would / be used to",
          "<b>used to</b> と <b>be used to</b> の違い。",
          ex=[("I <mark>used to live</mark> in Kyoto.", "私は以前、京都に住んでいた。"),
           ("When I was a child, I <mark>would often go</mark> fishing.", "子どものころ、よく釣りに行ったものだ。"),
           ("I <mark>am used to getting</mark> up early.", "私は早起きに慣れている。")],
          tip="<b>used to ＋原形 ＝ 以前は〜だった</b>（今はない。状態も表す）。<b>would ＝ よく〜したものだ</b>（動作の習慣のみ）。<b>be used to -ing ＝ 〜に慣れている</b>（get used to -ing ＝ 〜に慣れる）。<b>be used to do</b> は「〜するために使われる」で別の意味。"),
        i("sj-should-emotion", "core", "感情・判断を表す should",
          "<b>It is strange / natural / a pity ＋ that S should ＋ 原形</b>。",
          ex=[("It is strange that he <mark>should say</mark> such a thing.", "彼がそんなことを言うとは奇妙だ。"),
           ("It is natural that she <mark>should be</mark> angry.", "彼女が怒るのは当然だ。")],
          tip="<b>驚き・当然・遺憾</b>などの感情・判断を表す形容詞のあとの that 節に、should が入る。訳は「〜とは」「〜のは」。要求・提案の that 節（<a href=\"grammar.html#subjunctive-that\">原形／should</a>）と区別する。"),
        i("sj-need-dare", "skip", "need / dare の助動詞用法",
          "<b>need not do</b>（〜する必要はない）、<b>Dare he say so?</b>",
          line="出題は稀。<b>need not ＝ don't have to</b> だけ押さえれば十分。<b>dare</b> の助動詞用法は、出会ったときに意味を確認する程度でよい。"),
    ]),
    ],
    quiz=[
        ("次の文を訳しなさい。<br><i>If I had studied harder, I would have passed the exam.</i>",
         "<p><b class=\"a\">もっと勉強していれば、試験に合格していたのに。</b></p><p>仮定法過去完了。実際は「勉強しなかった／合格しなかった」。</p>"),
        ("次の文を、if を使った文に書き換えなさい。<br><i>Had I known the truth, I would have told you.</i>",
         "<p><b class=\"a\">If I had known the truth, I would have told you.</b></p><p>Had I p.p. ＝ If I had p.p.（if の省略による倒置）。</p>"),
        ("次の文を訳しなさい。<br><i>I wish I had studied harder.</i>",
         "<p><b class=\"a\">もっと勉強しておけばよかった。</b></p><p>wish ＋ had p.p. ＝ 過去への後悔。</p>"),
        ("used to と be used to の違いを、例文で答えなさい。<br><i>I used to get up early. ／ I am used to getting up early.</i>",
         "<p><b class=\"a\">前者：以前は早起きしていた（今はしない）／後者：早起きに慣れている</b></p><p>used to ＋ 原形は過去の習慣、be used to ＋ -ing は「慣れている」。</p>"),
    ],
)
