from content.base import i

PAGE = dict(
    file="p-verbal.html", key="vb", name="準動詞（不定詞・動名詞・分詞）",
    icon="🔧",
    summary="不定詞の意味上の主語・be to・too to、動名詞の慣用表現、分詞構文と with の付帯状況。",
    lead="動詞が形を変えて、名詞・形容詞・副詞の役をする。長文では「何を、どの語にかけているか」が問われる。",
    sections=[
    ("不定詞", [
        i("vb-sub-inf", "must", "不定詞の意味上の主語（for A to do / of A to do）",
          "to 不定詞の前に <b>for A</b> または <b>of A</b>。",
          ex=[("It is important <mark>for students to read</mark> carefully.", "学生が注意深く読むことは大切だ。"),
           ("It is kind <mark>of you to help</mark> me.", "私を助けてくれるとは、あなたは親切だ。")],
          tip="<b>for A to do ＝ A が〜すること</b>。<b>人の性質を表す形容詞</b>（kind, wise, careless, polite, rude, foolish）のときは <b>of A</b>。"),
        i("vb-perf-inf", "core", "完了不定詞（to have p.p.）と受動（to be p.p.）",
          "to の後ろが <b>have p.p.</b> または <b>be p.p.</b>。",
          ex=[("He seems <mark>to have made</mark> a mistake.", "彼は間違えたようだ。"),
           ("She is said <mark>to have been</mark> a singer.", "彼女は昔、歌手だったと言われている。"),
           ("This problem is <mark>to be solved</mark> soon.", "この問題はまもなく解決されることになっている。")],
          tip="<b>to have p.p.</b> は、<b>主節の動詞より前</b>の出来事。<b>seem / appear / be said / be believed ＋ to 不定詞</b>の形で多い。"),
        i("vb-be-to", "core", "be to 構文（予定・義務・可能・運命・意図）",
          "be 動詞のあとに <b>to 不定詞</b>が続く（受動態や進行形ではない）。",
          table=(["意味", "例"], [
              ["予定（〜することになっている）", "The meeting <b>is to</b> be held next week."],
              ["義務・命令（〜すべきだ）", "You <b>are to</b> finish it today."],
              ["可能（〜できる）※否定文が多い", "Not a star <b>was to</b> be seen."],
              ["運命（〜する運命だ）", "He <b>was never to</b> see his home again."],
              ["意図（〜するつもりなら）※if節内", "<b>If you are to</b> succeed, you must work hard."]]),
          tip="<b>文脈で意味を決める</b>。if 節の中なら意図、過去形で<b>never</b>があれば運命が多い。"),
        i("vb-indep-inf", "core", "独立不定詞（文全体にかかる慣用表現）",
          "文頭・文中の <b>to 〜</b> が、文全体を修飾する。",
          table=(["表現", "意味"], [
              ["to tell the truth", "実を言うと"],
              ["to be honest / to be frank", "正直に言うと"],
              ["to begin with", "まず第一に"],
              ["needless to say", "言うまでもなく"],
              ["so to speak", "いわば"],
              ["to make matters worse", "さらに悪いことに"],
              ["not to mention 〜", "〜は言うまでもなく"]]),
          ex=[("<mark>To be honest</mark>, I didn't like the plan.", "正直に言うと、私はその計画が好きではなかった。")],
          tip="決まった形なので、<b>かたまりで覚える</b>。構造を分析せず、訳をあてはめれば足りる。"),
        i("vb-too-enough", "must", "too ... to / ... enough to",
          "<b>too ＋形容詞・副詞 ＋ to do</b>、<b>形容詞 ＋ enough ＋ to do</b>。",
          ex=[("She is <mark>too young to travel</mark> alone.", "彼女は若すぎて、1人で旅行できない。"),
           ("He is <mark>old enough to vote</mark>.", "彼は投票できる年齢だ。"),
           ("He was <mark>kind enough to help</mark> me.", "彼は親切にも私を助けてくれた。")],
          tip="<b>too ... to ＝ 「〜すぎて…できない」</b>（否定的）。<b>enough to ＝ 「…するのに十分〜」</b>。<b>too ... for A to do</b> で意味上の主語を示す。",
          warn="<b>only too 〜</b>（とても〜だ）、<b>cannot ... too 〜</b>（いくら〜しても…しすぎない）と混同しない。<b>too heavy for me to carry</b> のように、to 不定詞の目的語が主語と同じものなら、it は入れない（× to carry it）。<b>so ... as to</b> は<a href=\"p-clause.html#cl-result\">結果・程度</a>を参照。"),
        i("vb-purpose-result", "core", "目的・結果の不定詞",
          "to 不定詞が<b>「〜するために」</b>か<b>「その結果〜」</b>かを決める。",
          ex=[("He studied hard <mark>in order to pass</mark> the exam.", "彼は試験に合格するために、熱心に勉強した。"),
           ("She grew up <mark>to be</mark> a doctor.", "彼女は成長して医者になった。"),
           ("He rushed to the station, <mark>only to find</mark> the train gone.", "彼は駅へ急いだが、電車はもう出たあとだった。")],
          tip="<b>in order to / so as to ＝ 目的</b>（否定は in order not to / so as not to）。<b>grow up to / live to / only to / never to ＝ 結果</b>（〜して、その結果…）。"),
        i("vb-bare-inf", "core", "原形不定詞を使う慣用表現",
          "<b>to のない不定詞</b>（原形）を後ろにとる表現。",
          table=(["表現", "意味・例"], [
              ["had better do", "〜したほうがよい：You had better see a doctor."],
              ["would rather do (than do)", "むしろ〜したい：I would rather stay home."],
              ["do nothing but do", "〜ばかりする：He did nothing but complain."],
              ["cannot but do", "〜せざるをえない：I cannot but admire her."],
              ["help O (to) do", "Oが〜するのを助ける"],
              ["Why not do 〜?", "〜したらどうか"]]),
          tip="<b>助動詞的な表現の後ろは原形</b>（to を入れない）。ただし <b>help O (to) do</b> は、to があってもなくてもよい。"),
        i("vb-substitute-inf", "core", "代不定詞と、不定詞の否定",
          "文の最後が <b>to だけ</b>になっている、または <b>not to do</b>。",
          ex=[("You may go if you <mark>want to</mark>.", "行きたければ、行ってもよい。（to の後ろの go が省略）"),
           ("He told me <mark>not to be</mark> late.", "彼は私に遅れないようにと言った。")],
          tip="<b>to だけが残る</b>のは、同じ動詞の繰り返しを避けているから（代不定詞）。<b>否定は to の直前</b>に not / never を置く。"),
    ]),
    ("動名詞", [
        i("vb-gerund-subj", "core", "動名詞の意味上の主語・否定・完了",
          "動名詞の<b>前</b>や<b>形</b>に、追加の情報がある。",
          ex=[("I don't mind <mark>his staying</mark> here.", "彼がここにいても構わない。"),
           ("She is proud of <mark>having won</mark> the prize.", "彼女はその賞を取ったことを誇りに思っている。"),
           ("He regrets <mark>not having studied</mark> harder.", "彼はもっと勉強しなかったことを後悔している。")],
          tip="<b>所有格（his）／目的格（him）</b>が意味上の主語。<b>having p.p.</b> は主節より前のこと。<b>否定は not ＋ -ing</b>。"),
        i("vb-gerund-idioms", "must", "動名詞を使う慣用表現",
          "<b>前置詞の to ＋ -ing</b> や、決まった型に注目。",
          table=(["表現", "意味"], [
              ["It is no use -ing", "〜しても無駄だ"],
              ["be worth -ing", "〜する価値がある"],
              ["cannot help -ing", "〜せずにはいられない"],
              ["feel like -ing", "〜したい気がする"],
              ["look forward to -ing", "〜を楽しみに待つ"],
              ["be used to -ing", "〜に慣れている"],
              ["object to -ing", "〜に反対する"],
              ["when it comes to -ing", "〜のことになると"],
              ["on -ing", "〜するとすぐに"],
              ["There is no -ing", "〜することはできない"],
              ["be busy -ing", "〜するのに忙しい"],
              ["spend 時間 -ing", "〜して時間を過ごす"],
              ["keep / stop / prevent A from -ing", "Aが〜するのを妨げる"]]),
          ex=[("This book is <mark>worth reading</mark> twice.", "この本は2回読む価値がある。")],
          tip="<b>この to は前置詞</b>（look forward to, be used to, object to）。だから後ろは動名詞。to 不定詞との見分けがポイント。",
          warn="<b>used to do（以前は〜した）</b>と<b>be used to -ing（〜に慣れている）</b>を混同しない。"),
    ]),
    ("分詞構文", [
        i("vb-participle-basic", "must", "分詞構文の基本",
          "文頭（または文中）の <b>-ing ＋語句 ,</b>。",
          ex=[("<mark>Walking along the street</mark>, I met an old friend.", "通りを歩いていると、旧友に会った。"),
           ("<mark>Not knowing what to do</mark>, she asked for help.", "どうしたらよいかわからなかったので、彼女は助けを求めた。")],
          tip="<b>意味上の主語は、主節の主語</b>。訳は<b>時（〜して・〜しながら）・理由・付帯状況・条件・譲歩</b>のうち、文脈で決める。接続詞を補って読むとわかりやすい。"),
        i("vb-participle-perf-pass", "must", "完了・受動の分詞構文",
          "<b>Having p.p.</b> または <b>(Being) p.p.</b> で始まる。",
          ex=[("<mark>Having finished</mark> the work, he went home.", "仕事を終えてから、彼は帰宅した。"),
           ("<mark>(Being) written</mark> in simple English, the book is easy to read.", "やさしい英語で書かれているので、その本は読みやすい。"),
           ("<mark>Seen from the sky</mark>, the island looks like a heart.", "空から見ると、その島はハートの形に見える。")],
          tip="<b>Having p.p. ＝ 主節より前の出来事</b>。<b>Being は省略される</b>ことが多く、文頭が p.p. のときは<b>「〜されて」</b>の受動の分詞構文。"),
        i("vb-absolute", "core", "独立分詞構文（主語が主節と違う）",
          "分詞の<b>前に、別の主語</b>がついている。",
          ex=[("<mark>Weather permitting</mark>, we will go camping.", "天気が良ければ、私たちはキャンプに行く。"),
           ("<mark>It being Sunday</mark>, the shop was closed.", "日曜日だったので、店は閉まっていた。")],
          tip="分詞の主語が主節と違うときは、<b>分詞の前に主語を置く</b>。<b>Weather permitting ＝ If the weather permits</b>のような定型もある。"),
        i("vb-with-oc", "must", "with ＋ O ＋ C（付帯状況）",
          "<b>with ＋ 名詞 ＋ 分詞・形容詞・副詞・前置詞句</b>。",
          ex=[("She was sitting <mark>with her legs crossed</mark>.", "彼女は脚を組んで座っていた。"),
           ("He listened <mark>with his eyes closed</mark>.", "彼は目を閉じて聞いていた。"),
           ("<mark>With the sun rising</mark>, the birds began to sing.", "太陽が昇る中、鳥たちが鳴き始めた。")],
          tip="<b>「〜しながら」「〜のままで」</b>。O と C は<b>主語と述語の関係</b>：C が -ing なら「〜している」、p.p. なら「〜されて」。"),
        i("vb-participle-idiom", "core", "分詞構文の慣用表現",
          "主語が決まっておらず、<b>文全体を修飾する</b>表現。",
          table=(["表現", "意味"], [
              ["generally speaking", "一般的に言えば"],
              ["judging from 〜", "〜から判断すると"],
              ["considering 〜 / given 〜", "〜を考えると"],
              ["speaking of 〜", "〜といえば"],
              ["taking 〜 into account", "〜を考慮に入れると"],
              ["providing / provided (that) 〜", "もし〜ならば"]]),
          ex=[("<mark>Judging from</mark> the look of the sky, it will rain soon.", "空模様から判断すると、まもなく雨が降る。")],
          tip="主語との関係を考えずに、<b>かたまりで訳す</b>。"),
        i("vb-conj-participle", "core", "接続詞つきの分詞構文",
          "<b>when / while / if / though ＋ -ing / p.p.</b>。",
          ex=[("<mark>While walking</mark> in the park, I found a wallet.", "公園を歩いていて、財布を見つけた。"),
           ("<mark>When asked</mark> about the plan, he refused to answer.", "その計画について聞かれたとき、彼は答えるのを断った。")],
          tip="意味をはっきりさせるため、接続詞が残っている。<b>接続詞＋（S be）の省略</b>と考えてもよい。主語は、主節の主語と同じ。"),
        i("vb-participle-adj", "must", "感情を表す分詞形容詞（interesting / interested）",
          "<b>-ing</b> と <b>p.p.</b> で、意味が逆になる。",
          table=(["-ing（〜させる）", "p.p.（〜させられる＝感じる）"], [
              ["exciting（わくわくさせる）", "excited（わくわくしている）"],
              ["boring（退屈させる）", "bored（退屈している）"],
              ["surprising（驚くべき）", "surprised（驚いた）"],
              ["tiring（疲れさせる）", "tired（疲れた）"],
              ["disappointing（がっかりさせる）", "disappointed（がっかりした）"]]),
          ex=[("The result was <mark>surprising</mark>.", "その結果は驚くべきものだった。"),
           ("I was <mark>surprised</mark> at the result.", "私はその結果に驚いた。")],
          tip="<b>感情を「与える」側（もの・こと）が -ing、「受ける」側（人）が p.p.</b>。主語が人か、ものかで決める。"),
    ]),
    ],
    quiz=[
        ("（　）に of / for のどちらが入るか。<br><i>It was careless (　　　) him to leave the door open.</i>",
         "<p><b class=\"a\">of</b></p><p>careless は人の性質を表す形容詞。for ではなく of ＋ 人。</p>"),
        ("次の文を訳しなさい。<br><i>He is too tired to go any further.</i>",
         "<p><b class=\"a\">彼は疲れすぎていて、これ以上先へは行けない。</b></p><p>too ... to do ＝ 〜すぎて…できない。</p>"),
        ("次の文を訳しなさい。<br><i>Considering his age, he is very active.</i>",
         "<p><b class=\"a\">彼の年齢を考えると、彼はとても活動的だ。</b></p><p>considering ＝ 〜を考えると（分詞構文の慣用表現）。</p>"),
        ("（　）に入る形を答えなさい。<br><i>I object to (　　　) treated like a child.</i>　ア. be　イ. being",
         "<p><b class=\"a\">イ. being</b></p><p>object to の to は前置詞なので、後ろは動名詞（being treated）。「子ども扱いされることに反対だ」。</p>"),
    ],
)
