from content.base import i

PAGE = dict(
    file="p-verbs.html", key="vs", name="動詞の型・語法",
    icon="🧭",
    summary="SVOC、使役・知覚、SVO to do、prevent A from -ing、regard A as B、無生物主語、It 構文、There 構文。",
    lead="動詞が決まれば、後ろに来る形も決まる。動詞ごとの「型」を知っていると、文の骨組みが先に読める。",
    sections=[
    ("動詞の後ろの形", [
        i("vs-svoc", "must", "SVOC（make / find / keep / leave / call / name）",
          "動詞のあとに、<b>O ＋ C</b>（O ＝ C の関係）。",
          ex=[("The news made <mark>us happy</mark>.", "その知らせは私たちを幸せにした。"),
           ("I found <mark>the book interesting</mark>.", "その本はおもしろいとわかった。"),
           ("They named <mark>the baby Emma</mark>.", "彼らは赤ちゃんをエマと名づけた。")],
          tip="<b>O ＝ C の関係（us ＝ happy）</b>。C は形容詞・名詞・分詞。<b>make / keep / leave / find / call / name / consider</b> がよく使われる。"),
        i("vs-causative", "must", "使役動詞（make / let / have / get）",
          "<b>make / let / have ＋ O ＋ 原形</b>、<b>get ＋ O ＋ to do</b>。",
          ex=[("The teacher <mark>made</mark> the students <mark>read</mark> the text aloud.", "先生は生徒に本文を音読させた。"),
           ("My mother <mark>let</mark> me <mark>go</mark>.", "母は私が行くのを許してくれた。"),
           ("I <mark>had</mark> my hair <mark>cut</mark>.", "私は髪を切ってもらった。"),
           ("I <mark>got</mark> him <mark>to fix</mark> my bike.", "私は彼に自転車を直してもらった。")],
          tip="<b>make（強制）／let（許可）／have（依頼）</b>の違い。<b>have ＋ O ＋ p.p. ＝ Oを〜してもらう／〜される</b>。",
          warn="<b>make の受動態は be made to do</b>（to が復活する）。<b>help ＋ O ＋ (to) do</b> は to を省略できる。"),
        i("vs-perception", "must", "知覚動詞（see / hear / feel / watch ＋ O ＋ 原形・-ing・p.p.）",
          "O のあとの形で、<b>見え方・聞こえ方</b>が変わる。",
          ex=[("I saw him <mark>cross</mark> the street.", "私は彼が通りを渡るのを（最初から最後まで）見た。"),
           ("I saw him <mark>crossing</mark> the street.", "私は彼が通りを渡っているところを見た。"),
           ("I heard my name <mark>called</mark>.", "私は自分の名前が呼ばれるのを聞いた。")],
          tip="<b>原形 ＝ 動作の全体</b>、<b>-ing ＝ 進行中</b>、<b>p.p. ＝ 〜される（受け身）</b>。"),
        i("vs-svo-to", "must", "SVO to do（O が〜するよう…する）",
          "動詞のあとが <b>O ＋ to 不定詞</b>。",
          ex=[("I <mark>want you to come</mark>.", "私はあなたに来てほしい。"),
           ("The rain <mark>forced us to cancel</mark> the game.", "雨のせいで、私たちは試合を中止せざるをえなかった。")],
          tip="<b>want / ask / tell / order / advise / allow / permit / enable / force / encourage / persuade / expect / cause</b> など。「Oが〜するように…する」と訳す。",
          warn="<b>suggest / propose / demand</b> は O ＋ to do の形をとれない（× suggest him to go）。that 節を使う（suggest that he go）。"),
        i("vs-from-ing", "must", "prevent / stop / keep A from -ing（Aが〜するのを妨げる）",
          "<b>動詞 ＋ A ＋ from ＋ -ing</b>。",
          ex=[("The heavy rain <mark>prevented us from going</mark> out.", "大雨のせいで、私たちは外出できなかった。"),
           ("Nothing can <mark>stop you from succeeding</mark>.", "何もあなたの成功を妨げられない。")],
          tip="<b>prevent / stop / keep / prohibit / discourage / hinder / ban ＋ A ＋ from -ing</b>。無生物主語なら、<b>「〜のせいでAは〜できない」</b>と訳す。"),
        i("vs-of", "core", "rob / deprive / inform / remind A of B（AからBを…する）",
          "<b>動詞 ＋ A ＋ of ＋ B</b>。",
          ex=[("The accident <mark>deprived him of</mark> his sight.", "その事故で、彼は視力を失った。"),
           ("The photo <mark>reminds me of</mark> my hometown.", "その写真を見ると、私は故郷を思い出す。"),
           ("She <mark>informed me of</mark> the change.", "彼女は私にその変更を知らせた。")],
          tip="<b>rob / deprive / cure / clear / relieve（奪う・取り除く）</b>、<b>inform / remind / convince / warn（知らせる）</b>。A に人・場所、B にものやことが来る（clear the road of snow のような形もある）。"),
        i("vs-with", "core", "provide / supply / equip A with B（AにBを与える）",
          "<b>動詞 ＋ A ＋ with ＋ B</b>。",
          ex=[("The school <mark>provides students with</mark> laptops.", "学校は生徒にノートパソコンを提供している。"),
           ("The room is <mark>equipped with</mark> air conditioning.", "その部屋にはエアコンが備わっている。")],
          tip="<b>provide / supply / equip / present / fill A with B</b>。<b>provide B for A</b> と書き換えられる。"),
        i("vs-as", "must", "regard / see / think of A as B（AをBとみなす）",
          "<b>動詞 ＋ A ＋ as ＋ B</b>。",
          ex=[("Many people <mark>regard him as</mark> a genius.", "多くの人が彼を天才だとみなしている。"),
           ("The report <mark>describes the city as</mark> a hub of trade.", "その報告書は、その都市を貿易の中心地と述べている。")],
          tip="<b>regard / see / look on / think of / take / describe / refer to / define A as B</b>。as は「として」。受動態は <b>be regarded as</b>。"),
    ]),
    ("構文としてのまとまり", [
        i("vs-inanimate", "must", "無生物主語構文（副詞的に訳す）",
          "<b>人ではないもの</b>が主語で、動詞が <b>make / enable / allow / prevent / lead / bring / take / show</b>。",
          ex=[("<mark>This app allows users</mark> to review words on the train.", "このアプリのおかげで、利用者は電車内で単語を復習できる。"),
           ("<mark>A few minutes' walk will take you</mark> to the station.", "数分歩けば、駅に着く。"),
           ("<mark>What brought you</mark> here?", "なぜここに来たのですか。")],
          tip="<b>主語を「〜のおかげで・〜によって・〜すると」と副詞的に訳し</b>、目的語（人）を主語のように扱う。"),
        i("vs-passive-note", "core", "受動態の注意（by 以外の前置詞など）",
          "受動態のあとに <b>by 以外の前置詞</b>が来る形。",
          table=(["表現", "意味"], [
              ["be known to 〜 / for 〜 / as 〜", "〜に知られている／〜で有名だ／〜として知られている"],
              ["be made of 〜 / from 〜", "〜でできている（材料）／〜からできている（原料）"],
              ["be surprised at 〜", "〜に驚く"],
              ["be interested in 〜", "〜に興味がある"],
              ["be satisfied with 〜", "〜に満足している"],
              ["be laughed at（群動詞の受動：前置詞 at を残す）", "笑われる"]]),
          ex=[("The mountain <mark>is covered with</mark> snow.", "その山は雪でおおわれている。")],
          tip="<b>感情を表す受動態</b>は、by ではなく別の前置詞をとることが多い。<b>群動詞は、前置詞を残したまま</b>受動態にする。"),
        i("vs-vt-vi", "core", "自動詞と他動詞の区別",
          "<b>目的語を直接とるか</b>、前置詞が必要か。",
          table=(["間違えやすい動詞", "正しい形"], [
              ["discuss", "discuss <b>the problem</b>（× discuss about）"],
              ["marry", "marry <b>her</b>（× marry with）"],
              ["enter / reach", "enter <b>the room</b>／reach <b>Tokyo</b>"],
              ["rise（自動詞）／raise（他動詞）", "The sun <b>rises</b>. ／ He <b>raised</b> his hand."],
              ["lie（自動詞）／lay（他動詞）", "lie down ／ lay the book on the desk"]]),
          tip="<b>他動詞の後ろに前置詞は不要</b>（discuss, marry, mention, resemble, attend, approach, enter, reach）。"),
        i("vs-reflexive", "core", "再帰代名詞（-self）を使う表現",
          "主語と目的語が<b>同じ人・もの</b>。",
          table=(["表現", "意味"], [
              ["enjoy oneself", "楽しむ"],
              ["help oneself to 〜", "〜を自由に取って食べる"],
              ["make oneself at home", "くつろぐ"],
              ["by oneself", "1人で"],
              ["for oneself", "自分で・自分のために"],
              ["in itself", "それ自体"],
              ["beside oneself", "我を忘れて"]]),
          ex=[("Please <mark>help yourself to</mark> the cake.", "どうぞケーキを召し上がってください。")],
          tip="<b>by oneself ＝ 1人で・独力で</b>、<b>for oneself ＝ 自分のために・自分で</b>。"),
        i("vs-it-pattern", "must", "It を使う構文のまとめ",
          "文頭の <b>It</b> が、後ろの節・不定詞を受けている。",
          table=(["形", "意味"], [
              ["It takes 人 時間 to do", "人が〜するのに…（時間）かかる"],
              ["It is 形容詞 for / of A to do", "Aが〜することは…だ"],
              ["It seems / appears that 〜", "〜のようだ"],
              ["It is said / believed that 〜", "〜と言われている／信じられている"],
              ["It turns out that 〜", "〜だとわかる"],
              ["It goes without saying that 〜", "〜は言うまでもない"],
              ["It occurs to 人 that 〜", "人に〜という考えが浮かぶ"],
              ["It is no use -ing", "〜しても無駄だ"]]),
          ex=[("<mark>It takes</mark> me an hour <mark>to get</mark> to school.", "私が学校に着くまで、1時間かかる。"),
              ("<mark>It turned out that</mark> he was right.", "結局、彼が正しいとわかった。")],
          tip="<b>It は仮の主語</b>。<b>It is said that S V ＝ S is said to V</b>（Sは〜と言われている）と書き換えられる。"),
        i("vs-there", "core", "There 構文（存在・出現）",
          "<b>There ＋ be / seem / remain / exist ＋ 名詞</b>。",
          ex=[("<mark>There remains</mark> a lot to be done.", "やるべきことがたくさん残っている。"),
              ("<mark>There seems to be</mark> a mistake.", "間違いがあるようだ。"),
              ("<mark>There is no telling</mark> what will happen.", "何が起こるかは、わからない。")],
          tip="<b>There が主語の位置にあるが、本当の主語は後ろの名詞</b>。<b>There is no -ing ＝ 〜することはできない</b>。"),
        i("vs-phrasal", "core", "群動詞（句動詞）の見抜き方",
          "<b>動詞 ＋ 副詞・前置詞</b>で、意味が変わる。",
          table=(["群動詞", "意味"], [
              ["look for / look after / look into", "探す／世話をする／調べる"],
              ["put off / put up with", "延期する／我慢する"],
              ["carry out / make up for", "実行する／埋め合わせる"],
              ["take after / come up with", "似ている／思いつく"],
              ["run out of / catch up with", "使い果たす／追いつく"],
              ["come across / look up to", "偶然出会う／尊敬する"]]),
          ex=[("The committee <mark>looked into</mark> the matter.", "委員会はその件を調べた。")],
          tip="<b>直訳せず、かたまりで意味を覚える</b>。<b>動詞＋副詞型</b>（put off, carry out, look up）で目的語が代名詞のときは<b>動詞＋代名詞＋副詞</b>の語順（put it off）。<b>動詞＋前置詞型</b>（look for, look after, look into）は<b>look for it</b> のまま。"),
        i("vs-tense", "core", "時制の使い分け（過去完了・現在完了進行・時制の一致）",
          "動詞の形が、<b>いつのことか</b>を決める。",
          ex=[("<mark>By the time</mark> I arrived, the meeting <mark>had already started</mark>.", "私が着いたときには、会議はもう始まっていた。"),
              ("I <mark>have been waiting</mark> for an hour.", "私は1時間ずっと待っている。"),
              ("She said that she <mark>was</mark> tired.", "彼女は疲れていると言った。")],
          tip="<b>過去完了 ＝ 過去のある時点より前</b>、<b>現在完了進行 ＝ ずっと〜している</b>。<b>時制の一致</b>：主節が過去なら、従属節の「現在」は過去に、「過去」は過去完了になる。<b>不変の真理・現在も続く事実・歴史的事実</b>は、時制の一致を受けない（He said that the earth goes round the sun.）。"),
    ]),
    ],
    quiz=[
        ("次の文を訳しなさい。<br><i>The heavy rain prevented us from going out.</i>",
         "<p><b class=\"a\">大雨のせいで、私たちは外出できなかった。</b></p><p>prevent A from -ing ＝ Aが〜するのを妨げる。無生物主語は原因として訳す。</p>"),
        ("意味の違いを答えなさい。<br><i>I saw him cross the street. ／ I saw him crossing the street.</i>",
         "<p><b class=\"a\">前者：渡るのを最初から最後まで見た ／ 後者：渡っている途中を見た</b></p><p>原形は動作の全体、-ing は進行中。</p>"),
        ("次の文を訳しなさい。<br><i>Many people regard him as a genius.</i>",
         "<p><b class=\"a\">多くの人が彼を天才だとみなしている。</b></p><p>regard A as B ＝ AをBとみなす。</p>"),
        ("it の中身を答えなさい。<br><i>It takes me an hour to get to school.</i>",
         "<p><b class=\"a\">to get to school（学校に着くこと）</b></p><p>形式主語の It。「学校に着くまで1時間かかる」。</p>"),
    ],
)
